-- Seed: real licensed cannabis retailers.
-- Generated by scripts/import-la-dispensaries.mjs from C:\Users\jetni\AppData\Local\Temp/de-licenses-geo.csv
-- Source: Delaware Office of the Marijuana Commissioner (official dispensaries page, manually transcribed 2026-07-01; geocoded via US Census batch geocoder). Public record / attribution.
-- Filter: all cities, active retailers + microbusiness + non-storefront.
-- Records: 13
insert into public.dispensaries
  (name, slug, address, city, state, zip, phone, email, website, license_number,
   is_medical, is_recreational, is_delivery, is_pickup, location, status)
values
  ('Best Buds Dover', 'best-buds-dover', '516 Jefferic Blvd', 'Dover', 'DE', '19901', null, null, null, 'DE-OMC-001', true, true, false, true, 'SRID=4326;POINT(-75.525927095379 39.178061232145)'::geography, 'active'),
  ('Best Buds Georgetown', 'best-buds-georgetown', '23 Georgetown Plaza', 'Georgetown', 'DE', '19947', null, null, null, 'DE-OMC-002', true, true, false, true, 'SRID=4326;POINT(-75.394999956495 38.67899259819)'::geography, 'active'),
  ('Columbia Care Wilmington', 'columbia-care-wilmington', '5608 Concord Pike', 'Wilmington', 'DE', '19803', null, null, null, 'DE-OMC-003', true, true, false, true, 'SRID=4326;POINT(-75.54309444823 39.833806438608)'::geography, 'active'),
  ('Columbia Care Smyrna', 'columbia-care-smyrna', '200 S. Dupont Hwy', 'Smyrna', 'DE', '19977', null, null, null, 'DE-OMC-004', true, true, false, true, 'SRID=4326;POINT(-75.601464496565 39.299304663678)'::geography, 'active'),
  ('Columbia Care Rehoboth Beach', 'columbia-care-rehoboth-beach', '36725 Bayside Outlet Dr', 'Rehoboth Beach', 'DE', '19971', null, null, null, 'DE-OMC-005', true, true, false, true, 'SRID=4326;POINT(-75.110470537576 38.715867703667)'::geography, 'active'),
  ('Field Supply Cannabis & Provisions', 'field-supply-cannabis-and-provisions', '4555 Kirkwood Hwy', 'Wilmington', 'DE', '19808', null, null, null, 'DE-OMC-006', true, true, false, true, 'SRID=4326;POINT(-75.656988135357 39.724594700715)'::geography, 'active'),
  ('Fresh Delaware Newark', 'fresh-delaware-newark', '800 Ogletown Rd', 'Newark', 'DE', '19711', null, null, null, 'DE-OMC-007', true, true, false, true, 'SRID=4326;POINT(-75.731476910205 39.68576592798)'::geography, 'active'),
  ('Fresh Delaware Milford', 'fresh-delaware-milford', '635 N. Dupont Blvd', 'Milford', 'DE', '19963', null, null, null, 'DE-OMC-008', true, true, false, true, 'SRID=4326;POINT(-75.441809165199 38.917093202686)'::geography, 'active'),
  ('The Farm Felton', 'the-farm-felton', '105 Irish Hills Rd', 'Felton', 'DE', '19943', null, null, null, 'DE-OMC-010', true, true, false, true, 'SRID=4326;POINT(-75.555718587187 39.042611196058)'::geography, 'active'),
  ('The Farm New Castle', 'the-farm-new-castle', '240 S. Dupont Hwy', 'New Castle', 'DE', '19720', null, null, null, 'DE-OMC-011', true, true, false, true, 'SRID=4326;POINT(-75.617488059216 39.653348604356)'::geography, 'active'),
  ('The Farm Frankford', 'the-farm-frankford', '34164 Dupont Blvd', 'Frankford', 'DE', '19945', null, null, null, 'DE-OMC-012', true, true, false, true, 'SRID=4326;POINT(-75.241237980219 38.518649350829)'::geography, 'active'),
  ('Thrive Dispensary Wilmington', 'thrive-dispensary-wilmington', '37 Germay Dr', 'Wilmington', 'DE', '19804', null, null, null, 'DE-OMC-013', true, true, false, true, 'SRID=4326;POINT(-75.578948918394 39.727652622528)'::geography, 'active'),
  ('Thrive Dispensary Lewes', 'thrive-dispensary-lewes', '12000 Old Vine Blvd Unit 102', 'Lewes', 'DE', '19958', null, null, null, 'DE-OMC-014', true, true, false, true, 'SRID=4326;POINT(-75.191288707522 38.741971719514)'::geography, 'active')
on conflict (slug) do nothing;
