-- Seed: real licensed cannabis retailers.
-- Generated by scripts/import-la-dispensaries.mjs from C:\Users\jetni\AppData\Local\Temp/nd-licenses-geo.csv
-- Source: North Dakota HHS (official dispensary-locations page, manually transcribed 2026-07-01; geocoded via US Census batch geocoder). Public record / attribution.
-- Filter: all cities, active retailers + microbusiness + non-storefront.
-- Records: 7
insert into public.dispensaries
  (name, slug, address, city, state, zip, phone, email, website, license_number,
   is_medical, is_recreational, is_delivery, is_pickup, location, status)
values
  ('Pure Dakota Health Of Bismarck', 'pure-dakota-health-of-bismarck', '1207 Memorial Highway', 'Bismarck', 'ND', '58501', null, null, null, 'ND-HHS-001', true, false, false, true, 'SRID=4326;POINT(-100.812148904151 46.807292372854)'::geography, 'active'),
  ('Strive Life', 'strive-life', '1809 13th Ave. North', 'Grand Forks', 'ND', '58201', null, null, null, 'ND-HHS-002', true, false, false, true, 'SRID=4326;POINT(-97.052051666009 47.932112387343)'::geography, 'active'),
  ('Curaleaf - Jamestown', 'curaleaf-jamestown', '1513 Business Loop East', 'Jamestown', 'ND', '58401', null, null, null, 'ND-HHS-004', true, false, false, true, 'SRID=4326;POINT(-98.687197284062 46.894579532283)'::geography, 'active'),
  ('Curaleaf - Dickinson', 'curaleaf-dickinson', '318 24th Street East', 'Dickinson', 'ND', '58601', null, null, null, 'ND-HHS-005', true, false, false, true, 'SRID=4326;POINT(-102.780393536723 46.90754414242)'::geography, 'active'),
  ('Curaleaf - Minot', 'curaleaf-minot', '2301 16th St. Sw', 'Minot', 'ND', '58701', null, null, null, 'ND-HHS-006', true, false, false, true, 'SRID=4326;POINT(-101.317495085186 48.209378900915)'::geography, 'active'),
  ('Pure Dakota Health - Fargo', 'pure-dakota-health-fargo', '4302 13th Ave. S. #19', 'Fargo', 'ND', '58103', null, null, null, 'ND-HHS-007', true, false, false, true, 'SRID=4326;POINT(-96.853544193111 46.861625008)'::geography, 'active'),
  ('Pure Dakota Health Of Williston', 'pure-dakota-health-of-williston', '120 26th Street East, Suite 500', 'Williston', 'ND', '58801', null, null, null, 'ND-HHS-008', true, false, false, true, 'SRID=4326;POINT(-103.621007064793 48.168655140848)'::geography, 'active')
on conflict (slug) do nothing;
