-- Seed: real licensed cannabis retailers.
-- Generated by scripts/import-la-dispensaries.mjs from C:\Users\jetni\AppData\Local\Temp/ky-licenses-geo.csv
-- Source: Kentucky Office of Medical Cannabis (official Find-a-Dispensary page, manually transcribed 2026-07-01; geocoded via US Census batch geocoder). Public record / attribution.
-- Filter: all cities, active retailers + microbusiness + non-storefront.
-- Records: 14
insert into public.dispensaries
  (name, slug, address, city, state, zip, phone, email, website, license_number,
   is_medical, is_recreational, is_delivery, is_pickup, location, status)
values
  ('Speakeasy Dispensary - Bowling Green', 'speakeasy-dispensary-bowling-green', '2708 Scottsville Rd, Ste A', 'Bowling Green', 'KY', '42104', null, null, null, 'KY-OMC-001', true, false, false, true, 'SRID=4326;POINT(-86.424283568642 36.948617547041)'::geography, 'active'),
  ('Barrio Capital Partners', 'barrio-capital-partners', '950 N Mulberry St, Suites 220a, 220b, 220c', 'Elizabethtown', 'KY', '42701', null, null, null, 'KY-OMC-002', true, false, false, true, 'SRID=4326;POINT(-85.842681270278 37.707049997551)'::geography, 'active'),
  ('Bd Expansion', 'bd-expansion', '1501-1641 Paris Pike', 'Georgetown', 'KY', '42324', null, null, null, 'KY-OMC-003', true, false, false, true, 'SRID=4326;POINT(-84.541787244652 38.21410252483)'::geography, 'active'),
  ('Bluegrass Cannacare', 'bluegrass-cannacare', '6809 Burlington Pike', 'Florence', 'KY', '41042', null, null, null, 'KY-OMC-004', true, false, false, true, 'SRID=4326;POINT(-84.628341544567 39.010797509254)'::geography, 'active'),
  ('Nuera Frankfort', 'nuera-frankfort', '325 Leonardwood Dr.', 'Frankfort', 'KY', '40601', null, null, null, 'KY-OMC-005', true, false, false, true, 'SRID=4326;POINT(-84.896568254936 38.161197059116)'::geography, 'active'),
  ('Blue Sage Cannabis Company', 'blue-sage-cannabis-company', '172 Imperial Way', 'Nicholasville', 'KY', '40356', null, null, null, 'KY-OMC-006', true, false, false, true, 'SRID=4326;POINT(-84.565912166649 37.902156624221)'::geography, 'active'),
  ('Speakeasy Dispensary - Nortonville', 'speakeasy-dispensary-nortonville', '140 N Hopkinsville St', 'Nortonville', 'KY', '42442', null, null, null, 'KY-OMC-007', true, false, false, true, 'SRID=4326;POINT(-87.451511468124 37.18633163322)'::geography, 'active'),
  ('Erh Ky', 'erh-ky', '140 Faith Assembly Church Rd', 'London', 'KY', '40741', null, null, null, 'KY-OMC-008', true, false, false, true, 'SRID=4326;POINT(-84.113136620992 37.148702725424)'::geography, 'active'),
  ('Speakeasy Dispensary - Lexington', 'speakeasy-dispensary-lexington', '1849 Alysheba Way', 'Lexington', 'KY', '40509', null, null, null, 'KY-OMC-009', true, false, false, true, 'SRID=4326;POINT(-84.419280839562 38.019654032003)'::geography, 'active'),
  ('Blue Sage - Oak Grove', 'blue-sage-oak-grove', '2624 Walter Garrett Ln', 'Oak Grove', 'KY', '42262', null, null, null, 'KY-OMC-010', true, false, false, true, 'SRID=4326;POINT(-87.408891226813 36.682514114629)'::geography, 'active'),
  ('Kentucky Alternative Care', 'kentucky-alternative-care', '2401-B Bardstown Rd', 'Louisville', 'KY', '40205', null, null, null, 'KY-OMC-012', true, false, false, true, 'SRID=4326;POINT(-85.688714144936 38.223850824222)'::geography, 'active'),
  ('Speakeasy Dispensary - Princeton', 'speakeasy-dispensary-princeton', '108 E. Main Street', 'Princeton', 'KY', '42445', null, null, null, 'KY-OMC-014', true, false, false, true, 'SRID=4326;POINT(-87.881846399107 37.108535535378)'::geography, 'active'),
  ('The Post Dispensary', 'the-post-dispensary', '300 N. Main St', 'Beaver Dam', 'KY', '42320', null, null, null, 'KY-OMC-015', true, false, false, true, 'SRID=4326;POINT(-86.875927745021 37.40398502633)'::geography, 'active'),
  ('Speakeasy Dispensary - Ashland', 'speakeasy-dispensary-ashland', '3508 Winchester Ave', 'Ashland', 'KY', '41101', null, null, null, 'KY-OMC-017', true, false, false, true, 'SRID=4326;POINT(-82.617903446914 38.465403305036)'::geography, 'active')
on conflict (slug) do nothing;
