-- Seed: real licensed cannabis retailers.
-- Generated by scripts/import-la-dispensaries.mjs from C:\Users\jetni\AppData\Local\Temp/va-licenses-geo.csv
-- Source: Virginia Cannabis Control Authority (official dispensary-locations page, manually transcribed 2026-07-01; geocoded via US Census batch geocoder). Public record / attribution.
-- Filter: all cities, active retailers + microbusiness + non-storefront.
-- Records: 21
insert into public.dispensaries
  (name, slug, address, city, state, zip, phone, email, website, license_number,
   is_medical, is_recreational, is_delivery, is_pickup, location, status)
values
  ('Beyond Hello Alexandria', 'beyond-hello-alexandria', '5902 Richmond Hwy, Suite 1', 'Alexandria', 'VA', '22303', '(703) 721-8722', null, null, 'VA-CCA-001', true, false, false, true, 'SRID=4326;POINT(-77.058468948948 38.791955228864)'::geography, 'active'),
  ('Beyond Hello Arlington', 'beyond-hello-arlington', '2701 Wilson Blvd', 'Arlington', 'VA', '22201', '(571) 895-7005', null, null, 'VA-CCA-002', true, false, false, true, 'SRID=4326;POINT(-77.090782334504 38.889661331626)'::geography, 'active'),
  ('Beyond Hello Fairfax', 'beyond-hello-fairfax', '10521 Fairfax Blvd', 'Fairfax', 'VA', '22030', '(571) 495-6999', null, null, 'VA-CCA-003', true, false, false, true, 'SRID=4326;POINT(-77.310961739268 38.856982250888)'::geography, 'active'),
  ('Beyond Hello Manassas', 'beyond-hello-manassas', '8100 Albertstone Circle', 'Manassas', 'VA', '20109', '(703) 420-4021', null, null, 'VA-CCA-004', true, false, false, true, 'SRID=4326;POINT(-77.561819997915 38.788810992496)'::geography, 'active'),
  ('Beyond Hello Sterling', 'beyond-hello-sterling', '21290 Windmill Parc Dr', 'Sterling', 'VA', '20166', '(276) 235-9700', null, null, 'VA-CCA-005', true, false, false, true, 'SRID=4326;POINT(-77.416662335899 39.026795802878)'::geography, 'active'),
  ('Beyond Hello Woodbridge', 'beyond-hello-woodbridge', '14400 Smoketown Rd', 'Woodbridge', 'VA', '22192', '(571) 677-4420', null, null, 'VA-CCA-006', true, false, false, true, 'SRID=4326;POINT(-77.300468500002 38.641367554376)'::geography, 'active'),
  ('Rise Abingdon', 'rise-abingdon', '26864 Watauga Rd', 'Abingdon', 'VA', '24211', '(276) 644-6400', null, null, 'VA-CCA-007', true, false, false, true, 'SRID=4326;POINT(-81.897600951898 36.722260142883)'::geography, 'active'),
  ('Rise Bristol', 'rise-bristol', '780 Gate City Hwy', 'Bristol', 'VA', '24201', '(276) 206-2003', null, null, 'VA-CCA-008', true, false, false, true, 'SRID=4326;POINT(-82.219533782391 36.601387030993)'::geography, 'active'),
  ('Rise Christiansburg', 'rise-christiansburg', '1675 Roanoke St', 'Christiansburg', 'VA', '24073', '(540) 251-4406', null, null, 'VA-CCA-009', true, false, false, true, 'SRID=4326;POINT(-80.37661749028 37.132989382862)'::geography, 'active'),
  ('Rise Danville', 'rise-danville', '816 West Main Street', 'Danville', 'VA', '24541', '(276) 644-6420', null, null, 'VA-CCA-010', true, false, false, true, 'SRID=4326;POINT(-79.422907109854 36.570557226591)'::geography, 'active'),
  ('Rise Lynchburg', 'rise-lynchburg', '3219 Old Forest Road', 'Lynchburg', 'VA', '24501', '(434) 363-3436', null, null, 'VA-CCA-011', true, false, false, true, 'SRID=4326;POINT(-79.212149220336 37.412333931837)'::geography, 'active'),
  ('Cannabist Carytown', 'cannabist-carytown', '3100 West Cary Street', 'Richmond', 'VA', '23221', '(804) 613-6121', null, null, 'VA-CCA-013', true, false, false, true, 'SRID=4326;POINT(-77.480143026861 37.553027592223)'::geography, 'active'),
  ('Cannabist Laburnum', 'cannabist-laburnum', '4320 South Laburnum Ave', 'Henrico', 'VA', '23231', '(804) 554-4880', null, null, 'VA-CCA-014', true, false, false, true, 'SRID=4326;POINT(-77.359553581932 37.530130024807)'::geography, 'active'),
  ('Gleaf Colonial Heights', 'gleaf-colonial-heights', '401 Southpark Blvd', 'Colonial Heights', 'VA', '23834', '(800) 484-0303', null, null, 'VA-CCA-015', true, false, false, true, 'SRID=4326;POINT(-77.394187093353 37.242838325664)'::geography, 'active'),
  ('Gleaf Richmond', 'gleaf-richmond', '2804 Decatur St, Building 30', 'Richmond', 'VA', '23224', '(800) 484-0303', null, null, 'VA-CCA-016', true, false, false, true, 'SRID=4326;POINT(-77.458288722377 37.510452780199)'::geography, 'active'),
  ('Gleaf Short Pump', 'gleaf-short-pump', '11190 West Broad Street', 'Glen Allen', 'VA', '23060', '(804) 613-5697', null, null, 'VA-CCA-017', true, false, false, true, 'SRID=4326;POINT(-77.600611944077 37.649299676367)'::geography, 'active'),
  ('Zen Leaf Norfolk', 'zen-leaf-norfolk', '7635 Granby Street', 'Norfolk', 'VA', '23505', '(757) 734-5880', null, null, 'VA-CCA-019', true, false, false, true, 'SRID=4326;POINT(-76.272731372457 36.915577342175)'::geography, 'active'),
  ('Zen Leaf Portsmouth', 'zen-leaf-portsmouth', '4012 Seaboard Court', 'Portsmouth', 'VA', '23701', '(757) 315-6808', null, null, 'VA-CCA-020', true, false, false, true, 'SRID=4326;POINT(-76.38114106203 36.799910436452)'::geography, 'active'),
  ('Zen Leaf Suffolk', 'zen-leaf-suffolk', '1238 Holland Road', 'Suffolk', 'VA', '23434', '(757) 538-7378', null, null, 'VA-CCA-021', true, false, false, true, 'SRID=4326;POINT(-76.615029186795 36.729815159272)'::geography, 'active'),
  ('Zen Leaf Virginia Beach', 'zen-leaf-virginia-beach', '535 North Birdneck Road', 'Virginia Beach', 'VA', '23451', '(757) 447-2303', null, null, 'VA-CCA-022', true, false, false, true, 'SRID=4326;POINT(-75.994411997519 36.849364995359)'::geography, 'active'),
  ('Zen Leaf Williamsburg', 'zen-leaf-williamsburg', '409 Bypass Rd', 'Williamsburg', 'VA', '23185', '(757) 734-4038', null, null, 'VA-CCA-023', true, false, false, true, 'SRID=4326;POINT(-76.713897523965 37.28489320115)'::geography, 'active')
on conflict (slug) do nothing;
