-- Enrich dispensaries with public phone/website from OpenStreetMap (ODbL).
-- Matched to OSM cannabis POIs requiring a distinctive shared name token within 150m.
-- Data (c) OpenStreetMap contributors.
-- Dispensaries enriched: 111

update public.dispensaries set phone = '+1 510-527-7827', website = 'https://www.7starshhc.com' where slug = '7-stars-holistic-healing-center';
update public.dispensaries set website = 'https://www.abatinsacramento.com' where slug = 'abatin-wellness-center';
update public.dispensaries set website = 'http://southbayhealingcenter.org/' where slug = 'airfield-supply-co';
update public.dispensaries set website = 'https://theauthenticcannabis.com/locations/authentic-415' where slug = 'authentic-415';
update public.dispensaries set phone = '+1-510-916-1267', website = 'https://www.stiiizy.com/pages/stiiizy-el-cerrito' where slug = 'authentic-el-cerrito-llc';
update public.dispensaries set phone = '+1 415-243-4400', website = 'http://barbarycoastsf.org' where slug = 'barbary-coast';
update public.dispensaries set phone = '+1 805-883-6444', website = 'https://beyond-hello.com/california-dispensaries/santa-barbara/' where slug = 'beyond-hello';
update public.dispensaries set phone = '+1-415-543-7666', website = 'https://www.bloomroom.com/' where slug = 'bloom-room';
update public.dispensaries set phone = '+1-213-353-0100', website = 'https://cc2go.com' where slug = 'california-caregivers-alliance';
update public.dispensaries set phone = '+1 415 800 7954', website = 'https://californiastreetcannabis.com/' where slug = 'california-street-cannabis-co';
update public.dispensaries set website = 'https://cannabis-culturessf.com' where slug = 'cannabis-cultures-equity-retailer';
update public.dispensaries set phone = '+1-707-757-5426', website = 'https://trycannavine.com/sr-cannabis-dispensary/' where slug = 'cannavine-santa-rosa';
update public.dispensaries set phone = '+1-805-560-0034', website = 'https://canopysb.com/' where slug = 'canopy-club-inc';
update public.dispensaries set phone = '+1-323-795-0323', website = 'https://catalyst-cannabis.com/dispensary-locations/mid-city-los-angeles-dispensary' where slug = 'catalyst-venice-blvd-equity-retailer';
update public.dispensaries set phone = '+1-323-265-7060', website = 'https://www.citycompassionatecaregivers.com/' where slug = 'city-compassionate-caregivers-inc';
update public.dispensaries set phone = '+1-209-762-3909', website = 'https://coastalcalifornia.com/location/coastal-stockton' where slug = 'coastal';
update public.dispensaries set phone = '+1-805-420-4000', website = 'https://coastalcalifornia.com/' where slug = 'coastal-dispensary-llc';
update public.dispensaries set phone = '+1-559-206-0529', website = 'https://www.cookiesfresno.co/' where slug = 'cookies-fresno';
update public.dispensaries set phone = '+1 916-231-9934', website = 'https://weedmaps.com/dispensaries/delta-health-and-wellness-2-4' where slug = 'delta-health-and-wellness-inc';
update public.dispensaries set website = 'https://doobienights.com/' where slug = 'doobie-nights-equity-retailer';
update public.dispensaries set phone = '+15598950091', website = 'https://doctorgreenthumbs.com/pages/dispensary-fresno/?utm_source=google&utm_medium=organic&utm_campaign=gmb' where slug = 'dr-greenthumb-s-fresno';
update public.dispensaries set website = 'https://eazedispensary.com' where slug = 'eaze-san-francisco-haight';
update public.dispensaries set phone = '+1-408-433-3344', website = 'https://elementalwellnesscenter.com/' where slug = 'elemental-wellness-center';
update public.dispensaries set website = 'https://www.stiiizy.com/' where slug = 'embarc-alameda';
update public.dispensaries set website = 'https://goembarc.com/' where slug = 'embarc-chico';
update public.dispensaries set phone = '+1-559-420-7999', website = 'https://goembarc.com/fresno-dispensary-blackstone-ave/' where slug = 'embarc-fresno';
update public.dispensaries set phone = '+1-559-481-6420', website = 'https://goembarc.com/madera-dispensary/' where slug = 'embarc-madera';
update public.dispensaries set phone = '+1 650 446 6006', website = 'https://goembarc.com/redwood-city-dispensary/' where slug = 'embarc-redwood-city';
update public.dispensaries set phone = '+1-916-572-9659', website = 'https://goembarc.com/sacramento-dispensary/' where slug = 'embarc-sacramento-equity-retailer';
update public.dispensaries set phone = '+1-310-616-5140', website = 'https://www.erbasawtelle.com' where slug = 'erba-sawtelle';
update public.dispensaries set website = 'https://farmacyshop.com/berkeley-dispensary/' where slug = 'farmacy-berkeley';
update public.dispensaries set phone = '+1 805-454-8473', website = 'https://farmacyshop.com/isla-vista-dispensary/' where slug = 'farmacy-isla-vista';
update public.dispensaries set phone = '+1 510 722 7768', website = 'https://florcalifornia.com/' where slug = 'flor';
update public.dispensaries set phone = '+1 415-869-8770' where slug = 'golden-gate-cannabis-company';
update public.dispensaries set phone = '+1-619-955-5540' where slug = 'goldn-bloom';
update public.dispensaries set website = 'https://www.grassrootssf.com/' where slug = 'grass-roots';
update public.dispensaries set phone = '+1-619-565-2837', website = 'https://ghbuds.com' where slug = 'grasshopper';
update public.dispensaries set phone = '+1-424-835-4203', website = 'https://www.thegreencitycollective.com' where slug = 'green-city-collective';
update public.dispensaries set phone = '+1-209-536-4208', website = 'https://hazybulldogdispensary.com/' where slug = 'hazy-bulldog-farms-llc';
update public.dispensaries set phone = '+1-510-838-2400', website = 'https://www.hifigreen.com/' where slug = 'hi-fidelity';
update public.dispensaries set website = 'https://www.highsierrajunelake.com/' where slug = 'high-sierra';
update public.dispensaries set phone = '+1-559-710-2420', website = 'https://www.tpg420.com/shophlfresno' where slug = 'higher-level-of-care';
update public.dispensaries set phone = '+1-707-826-7988' where slug = 'humboldt-s-premium';
update public.dispensaries set phone = '+1-707-496-0506', website = 'https://www.humboldtspremium.com/' where slug = 'humboldt-s-premium-eureka';
update public.dispensaries set website = 'https://www.jadeleafww.com/' where slug = 'jade-leaf';
update public.dispensaries set website = 'https://kiskanuhemp.com/' where slug = 'kiskanu-equity-retailer';
update public.dispensaries set phone = '+1 530-408-0420' where slug = 'la-florista';
update public.dispensaries set phone = '+1-310-429-3789', website = 'https://laxcc.com' where slug = 'lax-cannabis-club';
update public.dispensaries set phone = '+1-805-277-7798', website = 'https://legendaryorganics.com' where slug = 'legendary-organics-thousand-oaks';
update public.dispensaries set phone = '+1-650-735-9943', website = 'https://its-lytt.com/' where slug = 'lytt-llc';
update public.dispensaries set phone = '+1-530-231-5257', website = 'https://davismainstage.com' where slug = 'mainstage-davis';
update public.dispensaries set phone = '+1-760-934-5400', website = 'https://greenmammoth.com/' where slug = 'mammoth-roots-equity-retailer';
update public.dispensaries set phone = '+1-619-314-7336' where slug = 'march-and-ash-chula-vista';
update public.dispensaries set phone = '+1-760-362-6278' where slug = 'marvins-mary-j';
update public.dispensaries set phone = '+1-424-290-8030', website = 'https://www.medmen.com' where slug = 'medmen-lax';
update public.dispensaries set website = 'https://medmen.com/stores/los-angeles-west-hollywood/' where slug = 'medmen-weho';
update public.dispensaries set phone = '+1-805-592-1420', website = 'https://www.megansorganicmarket.com/' where slug = 'megan-s-organic-market';
update public.dispensaries set phone = '+1 805-576-9420', website = 'https://www.megansorganicmarket.com/location/goleta/' where slug = 'megan-s-organic-market-goleta';
update public.dispensaries set phone = '+1 323-522-3024', website = 'https://mota.la/' where slug = 'mota';
update public.dispensaries set phone = '+1-805-770-3275', website = 'https://oneplant.life/goleta/' where slug = 'one-plant';
update public.dispensaries set phone = '+1 831 789 9111' where slug = 'one-plant-monterey';
update public.dispensaries set website = 'https://oregrown.com/' where slug = 'oregrown';
update public.dispensaries set phone = '+1-707-843-4066', website = 'https://gophenotopia.com' where slug = 'phenotopia-equity-retailer';
update public.dispensaries set website = 'https://www.purplestarmd.com/about/' where slug = 'purple-star-md';
update public.dispensaries set phone = '+1 707-869-8008', website = 'https://riversidewellness.net/' where slug = 'riverside-wellness';
update public.dispensaries set website = 'https://rootd510.com/' where slug = 'root-d-in-the-510-equity-retailer';
update public.dispensaries set phone = '+1-760-606-7243', website = 'https://sageandfire.com' where slug = 'sage-and-fire-equity-retailer';
update public.dispensaries set phone = '+1-619-906-5546', website = 'https://www.sandiegorecreationalcannabis.com/' where slug = 'san-diego-recreational-cannabis-sdrc';
update public.dispensaries set phone = '+1-805-475-3957', website = 'https://www.stiiizy.com/pages/stiiizy-oxnard' where slug = 'sgi-oxnard-llc';
update public.dispensaries set phone = '+1-707-596-9040', website = 'https://solful.com/sebastopol/' where slug = 'solful';
update public.dispensaries set website = 'https://solful.com/' where slug = 'solful-healdsburg';
update public.dispensaries set phone = '+1-707-843-3227' where slug = 'sparc';
update public.dispensaries set phone = '+1-707-823-4206', website = 'https://sparc.co/' where slug = 'sparc-equity-retailer-sebastopol';
update public.dispensaries set phone = '+1-415-787-6006', website = 'https://www.stiiizy.com/pages/mission-dispensary' where slug = 'stiiizy';
update public.dispensaries set website = 'https://www.stiiizy.com/pages/stiiizy-costa-mesa' where slug = 'stiiizy-costa-mesa';
update public.dispensaries set website = 'https://www.stiiizy.com/pages/dtla-dispensary' where slug = 'stiiizy-dtla';
update public.dispensaries set phone = '+1 951-409-9054', website = 'https://www.stiiizy.com/pages/jurupa-valley-dispensary' where slug = 'stiiizy-jurupa-valley';
update public.dispensaries set phone = '+1-831-201-1795', website = 'https://www.stiiizy.com/pages/marina-dispensary' where slug = 'stiiizy-marina';
update public.dispensaries set phone = '+1-951-409-9670', website = 'https://www.stiiizy.com/pages/moreno-valley-dispensary' where slug = 'stiiizy-moreno-valley';
update public.dispensaries set phone = '+1-925-528-2420', website = 'https://www.stiiizy.com/pages/pacheco-dispensary' where slug = 'stiiizy-pacheco';
update public.dispensaries set phone = '+1-747-245-3421', website = 'https://www.stiiizy.com/pages/pacoima-dispensary' where slug = 'stiiizy-pacoima';
update public.dispensaries set phone = '+1-760-706-5118', website = 'https://www.stiiizy.com/pages/palm-desert-dispensary' where slug = 'stiiizy-palm-desert';
update public.dispensaries set phone = '+1-628-216-5717', website = 'https://www.stiiizy.com/pages/stiiizy-parkmerced' where slug = 'stiiizy-parkmerced';
update public.dispensaries set phone = '+1-909-325-3380', website = 'https://www.stiiizy.com/pages/pomona-dispensary' where slug = 'stiiizy-pomona';
update public.dispensaries set phone = '+1-628-254-1420', website = 'https://www.stiiizy.com/pages/stiiizy-soma' where slug = 'stiiizy-soma';
update public.dispensaries set phone = '+1 949-384-4279', website = 'https://www.stiiizy.com/pages/south-coast-dispensary' where slug = 'stiiizy-south-coast';
update public.dispensaries set phone = '+1 628 2585133', website = 'https://www.stiiizy.com/pages/union-square-dispensary' where slug = 'stiiizy-union-square';
update public.dispensaries set phone = '+1-707-360-6210', website = 'https://www.stiiizy.com/' where slug = 'stiizy-santa-rosa';
update public.dispensaries set website = 'https://sunsetpipeline.com' where slug = 'sunset-pipeline';
update public.dispensaries set phone = '+1 530 544-8000', website = 'https://www.tahoewellness.com/' where slug = 'tahoe-wellness-center-inc-equity-retailer';
update public.dispensaries set phone = '+1-760-663-7570', website = 'https://www.mammothholistics.com/' where slug = 'td-mammoth-inc';
update public.dispensaries set website = 'https://apothecarium.com/berkeley/' where slug = 'the-apothecarium-berkeley';
update public.dispensaries set phone = '+1-213-985-1815', website = 'https://www.theartisttree.com/los-angeles-dispensary/' where slug = 'the-artist-tree-equity-retailer';
update public.dispensaries set phone = '+1-559-258-0110', website = 'https://www.theartisttree.com/order-online-fresno/?utm_source=gmb&utm_campaign=dispenza' where slug = 'the-artist-tree-fresno';
update public.dispensaries set phone = '+1-310-626-1999', website = 'https://www.theartisttree.com/hawthorne-dispensary' where slug = 'the-artist-tree-inglewood';
update public.dispensaries set phone = '+1-619-844-5100', website = 'https://theblvddispensary.com' where slug = 'the-boulevard';
update public.dispensaries set phone = '+1 805-880-1207', website = 'https://farmacyshop.com/santa-barbara-dispensary/' where slug = 'the-farmacy';
update public.dispensaries set phone = '+1-707-826-7988' where slug = 'the-heart-of-humboldt';
update public.dispensaries set phone = '+1-831-515-7081', website = 'https://www.hookoutlet.com' where slug = 'the-hook-santa-cruz';
update public.dispensaries set phone = '+1-818-591-5899', website = 'https://www.canafarmscanoga.com' where slug = 'the-marathon-collective';
update public.dispensaries set phone = '+1-855-869-6337', website = 'https://www.themedicinewoman.com/pages/store-bellflower' where slug = 'the-medicine-woman';
update public.dispensaries set phone = '+1-916-309-4578', website = 'https://thepocketdispensary.com/' where slug = 'the-pocket-dispensary-equity-retailer';
update public.dispensaries set phone = '+1-323-452-9833', website = 'https://thepottery.la/' where slug = 'the-pottery';
update public.dispensaries set phone = '+1-760-709-2587', website = 'https://www.tiogagreen.com/' where slug = 'tioga-green-equity-retailer';
update public.dispensaries set phone = '+1-805-253-0956', website = 'https://shop.tradecraftfarms.com/port-hueneme/menu' where slug = 'tradecraft-farms-port-hueneme-llc';
update public.dispensaries set phone = '+1 415 702 6767', website = 'https://urbananow.com/' where slug = 'urbana-geary';
update public.dispensaries set phone = '+1-415-787-6006', website = 'https://www.stiiizy.com/pages/mission-dispensary' where slug = 'urbana-mission';
update public.dispensaries set website = 'https://urbnleaf.com' where slug = 'urbn-leaf';
update public.dispensaries set phone = '+1-424-264-5423' where slug = 'we-roll-up';
update public.dispensaries set phone = '+1-415-787-3688' where slug = 'weedhub-equity-retailer';
update public.dispensaries set phone = '+1-619-353-9577', website = 'https://www.wellgreens.store/location/lemon-grove' where slug = 'wellgreens-dispensary-lemon-grove';
