-- Seed: real licensed cannabis retailers.
-- Generated by scripts/import-la-dispensaries.mjs from C:\Users\jetni\AppData\Local\Temp/nh-licenses-geo.csv
-- Source: New Hampshire DHHS ATC program (operator sites cross-referenced 2026-07-01; geocoded via US Census batch geocoder). Public record / attribution.
-- Filter: all cities, active retailers + microbusiness + non-storefront.
-- Records: 4
insert into public.dispensaries
  (name, slug, address, city, state, zip, phone, email, website, license_number,
   is_medical, is_recreational, is_delivery, is_pickup, location, status)
values
  ('Graniteleaf Cannabis - Chichester', 'graniteleaf-cannabis-chichester', '349 Dover Road (Route 4)', 'Chichester', 'NH', '03258', '603-212-1500', null, null, 'NH-DHHS-002', true, false, false, true, 'SRID=4326;POINT(-71.441545520102 43.244555877375)'::geography, 'active'),
  ('Sanctuary Atc - Conway', 'sanctuary-atc-conway', '234 White Mountain Hwy', 'Conway', 'NH', '03818', '603-662-0113', null, null, 'NH-DHHS-004', true, false, false, true, 'SRID=4326;POINT(-71.112278832889 43.985083787135)'::geography, 'active'),
  ('Temescal Wellness - Dover', 'temescal-wellness-dover', '26 Crosby Road, Units 11-12', 'Dover', 'NH', '03820', '603-285-9383', null, null, 'NH-DHHS-005', true, false, false, true, 'SRID=4326;POINT(-70.916054114423 43.187346968894)'::geography, 'active'),
  ('Temescal Wellness - Keene', 'temescal-wellness-keene', '69 Island St Suite 1', 'Keene', 'NH', '03431', '603-285-9383', null, null, 'NH-DHHS-007', true, false, false, true, 'SRID=4326;POINT(-72.288119343518 42.930218344836)'::geography, 'active')
on conflict (slug) do nothing;
