-- Seed: curated real California cannabis consumer brands.
-- Hand-curated (no public brand registry exists; not scraped). Unowned —
-- brand owners can claim and enrich these listings later.
-- Brands: 99
insert into public.brands (name, slug, description)
values
  ('Connected Cannabis Co.', 'connected-cannabis-co', 'California cannabis flower brand.'),
  ('Alien Labs', 'alien-labs', 'California cannabis flower brand.'),
  ('Jungle Boys', 'jungle-boys', 'California cannabis flower brand.'),
  ('Wonderbrett', 'wonderbrett', 'California cannabis flower brand.'),
  ('Sherbinskis', 'sherbinskis', 'California cannabis flower brand.'),
  ('Backpack Boyz', 'backpack-boyz', 'California cannabis flower brand.'),
  ('Lemonnade', 'lemonnade', 'California cannabis flower brand.'),
  ('Cookies', 'cookies', 'California cannabis flower brand.'),
  ('Glass House Farms', 'glass-house-farms', 'California cannabis flower brand.'),
  ('Pacific Stone', 'pacific-stone', 'California cannabis flower brand.'),
  ('Lowell Farms', 'lowell-farms', 'California cannabis flower brand.'),
  ('Claybourne Co.', 'claybourne-co', 'California cannabis flower brand.'),
  ('Cream of the Crop', 'cream-of-the-crop', 'California cannabis flower brand.'),
  ('Almora Farm', 'almora-farm', 'California cannabis flower brand.'),
  ('Fig Farms', 'fig-farms', 'California cannabis flower brand.'),
  ('Maven Genetics', 'maven-genetics', 'California cannabis flower brand.'),
  ('Source Cannabis', 'source-cannabis', 'California cannabis flower brand.'),
  ('Henry''s Original', 'henry-s-original', 'California cannabis flower brand.'),
  ('Flow Kana', 'flow-kana', 'California cannabis flower brand.'),
  ('Coastal Sun Farm', 'coastal-sun-farm', 'California cannabis flower brand.'),
  ('Sonoma Hills Farm', 'sonoma-hills-farm', 'California cannabis flower brand.'),
  ('Aster Farms', 'aster-farms', 'California cannabis flower brand.'),
  ('Ball Family Farms', 'ball-family-farms', 'California cannabis flower brand.'),
  ('Pure Beauty', 'pure-beauty', 'California cannabis flower brand.'),
  ('Cypress Cannabis', 'cypress-cannabis', 'California cannabis flower brand.'),
  ('Grandiflora', 'grandiflora', 'California cannabis flower brand.'),
  ('Humboldt''s Finest', 'humboldt-s-finest', 'California cannabis flower brand.'),
  ('Humboldt Farms', 'humboldt-farms', 'California cannabis flower brand.'),
  ('Nug', 'nug', 'California cannabis flower brand.'),
  ('Stone Road', 'stone-road', 'California cannabis flower brand.'),
  ('Allswell', 'allswell', 'California cannabis flower brand.'),
  ('Pacific Reserve', 'pacific-reserve', 'California cannabis flower brand.'),
  ('Local Cannabis Co.', 'local-cannabis-co', 'California cannabis flower brand.'),
  ('Emerald Spirit Botanicals', 'emerald-spirit-botanicals', 'California cannabis flower brand.'),
  ('Gelato', 'gelato', 'California cannabis flower brand.'),
  ('THC Design', 'thc-design', 'California cannabis flower brand.'),
  ('The Growers Circle', 'the-growers-circle', 'California cannabis flower brand.'),
  ('Field Extracts', 'field-extracts', 'California cannabis concentrate & extract brand.'),
  ('Stiiizy', 'stiiizy', 'California cannabis vape & concentrate brand.'),
  ('Raw Garden', 'raw-garden', 'California cannabis concentrate & extract brand.'),
  ('Heavy Hitters', 'heavy-hitters', 'California cannabis vape & concentrate brand.'),
  ('Select', 'select', 'California cannabis vape & concentrate brand.'),
  ('Rove', 'rove', 'California cannabis vape & concentrate brand.'),
  ('PLUGplay', 'plugplay', 'California cannabis vape & concentrate brand.'),
  ('Friendly Farms', 'friendly-farms', 'California cannabis vape & concentrate brand.'),
  ('AbsoluteXtracts', 'absolutextracts', 'California cannabis vape & concentrate brand.'),
  ('Beezle Extracts', 'beezle-extracts', 'California cannabis concentrate & extract brand.'),
  ('710 Labs', '710-labs', 'California cannabis concentrate & extract brand.'),
  ('Jetty Extracts', 'jetty-extracts', 'California cannabis vape & concentrate brand.'),
  ('West Coast Cure', 'west-coast-cure', 'California cannabis vape & concentrate brand.'),
  ('Kurvana', 'kurvana', 'California cannabis vape & concentrate brand.'),
  ('Bloom Brands', 'bloom-brands', 'California cannabis vape & concentrate brand.'),
  ('Cannabiotix', 'cannabiotix', 'California cannabis flower brand.'),
  ('Moxie', 'moxie', 'California cannabis concentrate & extract brand.'),
  ('Guild Extracts', 'guild-extracts', 'California cannabis concentrate & extract brand.'),
  ('Pure Vape', 'pure-vape', 'California cannabis vape & concentrate brand.'),
  ('Korova', 'korova', 'California cannabis flower brand.'),
  ('Dabwoods', 'dabwoods', 'California cannabis vape & concentrate brand.'),
  ('710 Kingpen', '710-kingpen', 'California cannabis vape & concentrate brand.'),
  ('Loudpack', 'loudpack', 'California cannabis flower brand.'),
  ('Papa''s Select', 'papa-s-select', 'California cannabis concentrate & extract brand.'),
  ('Dime Industries', 'dime-industries', 'California cannabis vape & concentrate brand.'),
  ('Dompen', 'dompen', 'California cannabis vape & concentrate brand.'),
  ('Litto', 'litto', 'California cannabis vape & concentrate brand.'),
  ('Eureka', 'eureka', 'California cannabis vape & concentrate brand.'),
  ('Packwoods', 'packwoods', 'California cannabis pre-roll brand.'),
  ('Wyld', 'wyld', 'California cannabis edibles brand.'),
  ('Kiva', 'kiva', 'California cannabis edibles brand.'),
  ('Camino', 'camino', 'California cannabis edibles brand.'),
  ('Petra', 'petra', 'California cannabis edibles brand.'),
  ('Lost Farm', 'lost-farm', 'California cannabis edibles brand.'),
  ('Kanha', 'kanha', 'California cannabis edibles brand.'),
  ('Wana Brands', 'wana-brands', 'California cannabis edibles brand.'),
  ('PLUS Products', 'plus-products', 'California cannabis edibles brand.'),
  ('Papa & Barkley', 'papa-and-barkley', 'California cannabis wellness & tincture brand.'),
  ('Mary''s Medicinals', 'mary-s-medicinals', 'California cannabis wellness & tincture brand.'),
  ('Yummi Karma', 'yummi-karma', 'California cannabis wellness & tincture brand.'),
  ('Froot', 'froot', 'California cannabis edibles brand.'),
  ('Smokiez Edibles', 'smokiez-edibles', 'California cannabis edibles brand.'),
  ('Punch Edibles', 'punch-edibles', 'California cannabis edibles brand.'),
  ('Breez', 'breez', 'California cannabis wellness & tincture brand.'),
  ('Cann', 'cann', 'California cannabis beverage brand.'),
  ('Keef', 'keef', 'California cannabis beverage brand.'),
  ('Pabst Labs', 'pabst-labs', 'California cannabis beverage brand.'),
  ('Uncle Arnie''s', 'uncle-arnie-s', 'California cannabis beverage brand.'),
  ('Lord Jones', 'lord-jones', 'California cannabis edibles brand.'),
  ('Garden Society', 'garden-society', 'California cannabis edibles brand.'),
  ('Hervé', 'herve', 'California cannabis edibles brand.'),
  ('Dr. Norm''s', 'dr-norm-s', 'California cannabis edibles brand.'),
  ('Kikoko', 'kikoko', 'California cannabis beverage brand.'),
  ('Care By Design', 'care-by-design', 'California cannabis wellness & tincture brand.'),
  ('Jeeter', 'jeeter', 'California cannabis pre-roll brand.'),
  ('El Blunto', 'el-blunto', 'California cannabis pre-roll brand.'),
  ('Space Coyote', 'space-coyote', 'California cannabis pre-roll brand.'),
  ('Drew Martin', 'drew-martin', 'California cannabis pre-roll brand.'),
  ('Dogwalkers', 'dogwalkers', 'California cannabis pre-roll brand.'),
  ('Caliva', 'caliva', 'California cannabis brand.'),
  ('Fun Uncle', 'fun-uncle', 'California cannabis vape & concentrate brand.'),
  ('Old Pal', 'old-pal', 'California cannabis flower brand.')
on conflict (slug) do nothing;
