-- Seed: real licensed cannabis retailers.
-- Generated by scripts/import-la-dispensaries.mjs from C:\Users\jetni\AppData\Local\Temp/al-licenses-geo.csv
-- Source: Alabama Medical Cannabis Commission (first confirmed-open dispensary, per Alabama Reflector/MJBizDaily reporting 2026-06-04; geocoded via US Census batch geocoder). Public record / attribution.
-- Filter: all cities, active retailers + microbusiness + non-storefront.
-- Records: 1
insert into public.dispensaries
  (name, slug, address, city, state, zip, phone, email, website, license_number,
   is_medical, is_recreational, is_delivery, is_pickup, location, status)
values
  ('Callie''s Apothecary', 'callie-s-apothecary', '5232 Atlanta Highway', 'Montgomery', 'AL', '36109', null, null, 'https://shoppecalliesal.com/', 'AL-AMCC-001', true, false, false, true, 'SRID=4326;POINT(-86.219684008098 32.381700148242)'::geography, 'active')
on conflict (slug) do nothing;
