-- Backfill NY legal_name from OCM entity_name, matched by license_number.

update public.dispensaries set legal_name = 'Rman Holdings LLC' where slug = 'kaya-bliss-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Kushmart Ny, LLC' where slug = 'kushmart' and legal_name is null;
update public.dispensaries set legal_name = 'Saratoga Vapor Shop, LLC' where slug = 'leaf-and-fog' and legal_name is null;
update public.dispensaries set legal_name = 'Whiteboxthc, LLC' where slug = 'lenox-hill-cannabis-co' and legal_name is null;
update public.dispensaries set legal_name = 'Weed Growers From Seed To Stone LLC' where slug = 'matawana' and legal_name is null;
update public.dispensaries set legal_name = 'Cannary LLC' where slug = 'mrs-green-s-cannary' and legal_name is null;
update public.dispensaries set legal_name = 'Planet 51 LLC' where slug = 'nicklz' and legal_name is null;
update public.dispensaries set legal_name = 'Nucleus Dispensary INC.' where slug = 'nucleus-dispensary-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Orange County Cannabis LLC' where slug = 'orange-county-cannabis-co' and legal_name is null;
update public.dispensaries set legal_name = 'Aqr Development Funding LLC' where slug = 'planet-nugg' and legal_name is null;
update public.dispensaries set legal_name = 'Smmb, INC' where slug = 'purple-plains' and legal_name is null;
update public.dispensaries set legal_name = 'Parra''S Enterprises, LLC' where slug = 'satisfied-mind' and legal_name is null;
update public.dispensaries set legal_name = 'Secret Garden 716 LLC' where slug = 'secret-garden-716' and legal_name is null;
update public.dispensaries set legal_name = 'Tcma LLC' where slug = 'sofaclub-cannabis' and legal_name is null;
update public.dispensaries set legal_name = 'Dekalbcmm LLC' where slug = 'soulmate' and legal_name is null;
update public.dispensaries set legal_name = 'Ymrm Dispensary LLC' where slug = 'stash-box' and legal_name is null;
update public.dispensaries set legal_name = 'State Of Mind Dispensary, LLC' where slug = 'state-of-mind-dispensary-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Strains For Life, Corp' where slug = 'strains-for-life-powered-by-indoor-treez' and legal_name is null;
update public.dispensaries set legal_name = 'Keller Gutierrez LLC' where slug = 'the-cannabis-reserve' and legal_name is null;
update public.dispensaries set legal_name = 'The Kokoro Way, LLC' where slug = 'the-kokoro-way-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Tiki Leaves LLC' where slug = 'tiki-leaves-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Mad Ny 1' where slug = 'tru-cannabis' and legal_name is null;
update public.dispensaries set legal_name = 'Twisted Cannabis Flx LLC' where slug = 'twisted-cannabis-flx' and legal_name is null;
update public.dispensaries set legal_name = 'The Doe Store LLC' where slug = 'union-square-travel-agency-a-cannabis-store' and legal_name is null;
update public.dispensaries set legal_name = 'Upstate Pines INC.' where slug = 'upstate-pines' and legal_name is null;
update public.dispensaries set legal_name = 'Soodaks, INC.' where slug = 'verdi' and legal_name is null;
update public.dispensaries set legal_name = 'New Metro Enterprise INC' where slug = 'weed-mart-by-new-metro' and legal_name is null;
update public.dispensaries set legal_name = '1wilde1 LLC' where slug = 'wilde-roots-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Yonkers Dream LLC' where slug = 'yonkers-dream-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Housing Works Cannabis, LLC' where slug = 'housing-works-cannabis-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Vj Farms LLC' where slug = 'vj-farms-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Upstate Haze LLC' where slug = 'upstate-haze-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Dagga LLC' where slug = 'dagga-llc' and legal_name is null;
update public.dispensaries set legal_name = '716 Cannabis' where slug = '716-cannabis' and legal_name is null;
update public.dispensaries set legal_name = 'Cannadreams INC.' where slug = 'cannadreams-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Srcg LLC' where slug = 'cannafamily-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Cloud 9 Dispensary, LLC' where slug = 'cloud-9-dispensary-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Cloud 9 Smoke & Gift Shop INC.' where slug = 'cloud-9-smoke-and-gift-shop-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Green Rush 607 LLC' where slug = 'culture-cannabis-company' and legal_name is null;
update public.dispensaries set legal_name = 'Dankley LLC' where slug = 'dankley-canna' and legal_name is null;
update public.dispensaries set legal_name = 'Demarino''S, LLC' where slug = 'demarino-s-llc' and legal_name is null;
update public.dispensaries set legal_name = 'The Highest Peak LLC' where slug = 'the-highest-peak-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Ellenville Cannabis LLC' where slug = 'ellenville-cannabis-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Rosedale Cannabis Dispensary LLC' where slug = 'esh' and legal_name is null;
update public.dispensaries set legal_name = 'Farmers Choice Dispensary 2 LLC' where slug = 'farmers-choice-dispensary-2-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Jtcc Ny LLC' where slug = 'fingerlakes-cannabis-co' and legal_name is null;
update public.dispensaries set legal_name = 'Twin Acres Estates, INC.' where slug = 'twin-acres-estates-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Green Enterprise Holdings LLC' where slug = 'flower-power-dispensers-maspeth' and legal_name is null;
update public.dispensaries set legal_name = 'Robert L Grannis LLC' where slug = 'flynnstoned-cannabis-company-binghamton' and legal_name is null;
update public.dispensaries set legal_name = 'Nitecap LLC' where slug = 'nitecap-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Victory Road Farm, LLC' where slug = 'victory-road-farm-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Essential Flowers' where slug = 'legacy-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Oet INC.' where slug = 'oet-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Brain Bloom LLC' where slug = 'flynnstoned-cannabis-company-brooklyn' and legal_name is null;
update public.dispensaries set legal_name = 'Green Empire Wellness LLC' where slug = 'gaslight-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Good Grades LLC' where slug = 'good-grades-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Mach Enterprises Of Ny LLC' where slug = 'good-life-collective' and legal_name is null;
update public.dispensaries set legal_name = 'Green Apple Distribution Ltd.' where slug = 'green-apple-distribution-ltd' and legal_name is null;
update public.dispensaries set legal_name = 'Nube Nyc LLC' where slug = 'nube-nyc-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Ny Retail 2 INC.' where slug = 'ny-retail-2-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Green Comfort INC.' where slug = 'green-comfort-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Barone Partners LLC' where slug = 'grounded' and legal_name is null;
update public.dispensaries set legal_name = 'Purple Provisions, LLC' where slug = 'happy-times-cannabis-co' and legal_name is null;
update public.dispensaries set legal_name = 'North Country Roots, INC.' where slug = 'elevate-adk' and legal_name is null;
update public.dispensaries set legal_name = 'Highlife Health, LLC' where slug = 'highlife-health-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Psuw LLC' where slug = 'psuw-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Greenery Spot LLC' where slug = 'greenery-spot-llc' and legal_name is null;
update public.dispensaries set legal_name = '7420 Utrecht LLC' where slug = '7420-utrecht-llc' and legal_name is null;
update public.dispensaries set legal_name = '2147 44th LLC' where slug = '2147-44th-llc' and legal_name is null;
update public.dispensaries set legal_name = 'High End Dispensary Roc LLC' where slug = 'high-end-new-york' and legal_name is null;
update public.dispensaries set legal_name = 'Nelsonskickz LLC' where slug = 'the-firehaus-ny' and legal_name is null;
update public.dispensaries set legal_name = 'Lakehouse Cannabis, LLC' where slug = 'lakehouse-cannabis-llc' and legal_name is null;
update public.dispensaries set legal_name = 'The Phinest Buds LLC' where slug = 'the-phinest-buds-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Exotic Herbals LLC' where slug = 'exotic-herbals-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Bitar Assets INC.' where slug = 'flor-de-fred' and legal_name is null;
update public.dispensaries set legal_name = 'Mizzor Collection LLC' where slug = 'rezidue' and legal_name is null;
update public.dispensaries set legal_name = 'Monticello Cannabis LLC' where slug = 'monticello-cannabis-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Stage One Cannabis LLC' where slug = 'stage-one-cannabis-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Tango Hotel Charlie Ventures LLC' where slug = 'the-travel-agency-soho' and legal_name is null;
update public.dispensaries set legal_name = 'Greenlakesdispo, L.L.C.' where slug = 'flynnstoned-cannabis-company-rochester' and legal_name is null;
update public.dispensaries set legal_name = 'Beyond Beleaf Ny INC' where slug = 'beleaf-calverton' and legal_name is null;
update public.dispensaries set legal_name = 'Rockaway Beach Cafe INC.' where slug = 'rockaway-beach-cafe-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Calmunity Farms LLC' where slug = 'calmunity-farms-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Georgia Heights, LLC' where slug = 'georgia-heights-llc' and legal_name is null;
update public.dispensaries set legal_name = '720 Winton Road LLC' where slug = '720-winton-road-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Jupiter Cafe LLC' where slug = 'jupter-cafe' and legal_name is null;
update public.dispensaries set legal_name = 'High Points Of The Finger Lakes, LLC' where slug = 'high-points-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Leafy Wonders LLC' where slug = 'leafy-wonders' and legal_name is null;
update public.dispensaries set legal_name = 'Gotham Buds LLC' where slug = 'gotham-buds-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Organic Blooms LLC' where slug = 'organic-blooms-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Ntnr Dispensary LLC' where slug = 'ntnr-dispensary-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Upstateny Cannabis, LLC' where slug = 'upstateny-cannabis-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Green Jungle INC.' where slug = 'cannavita' and legal_name is null;
update public.dispensaries set legal_name = 'The Brooklyn Green Project LLC' where slug = 'sunset-cannabis-club' and legal_name is null;
update public.dispensaries set legal_name = 'Rustik 471, LLC' where slug = 'rustik-471-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Mark L Cold' where slug = 'society-of-the-seven-sages' and legal_name is null;
update public.dispensaries set legal_name = 'Birchwyn & Tess LLC' where slug = 'east-end-arrivals' and legal_name is null;
update public.dispensaries set legal_name = 'Waterman''S Greenhouse LLC' where slug = 'greenside-cannabis' and legal_name is null;
update public.dispensaries set legal_name = 'Ny Cj Ball INC' where slug = 'ny-cj-ball-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Geneva Naturals LLC' where slug = 'dryden-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'The Chosen Pot LLC' where slug = 'the-chosen-pot' and legal_name is null;
update public.dispensaries set legal_name = 'Northfield Consulting LLC' where slug = 'the-shady-grove-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Sparkboro INC' where slug = 'sparkboro-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Carry-On Cannabis Ny LLC' where slug = 'carry-on-cannabis-ny-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Rosedale Cannabis Dispensary LLC' where slug = 'rosedale-cannabis-dispensary-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Gourmet Budz LLC' where slug = 'gourmet-budz-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Bud Dispensary Company, LLC' where slug = 'bud-dispensary-company-llc' and legal_name is null;
update public.dispensaries set legal_name = 'New York Tetrahydrocannabinol Company L.L.C.' where slug = 'tetra' and legal_name is null;
update public.dispensaries set legal_name = 'Realistic Health & Wellness' where slug = 'realistic-health-and-wellness' and legal_name is null;
update public.dispensaries set legal_name = 'A Little Place To Relax LLC' where slug = 'just-a-little-higher-murray-hill' and legal_name is null;
update public.dispensaries set legal_name = 'Budding Industry Group LLC' where slug = 'long-island-cannabis-club' and legal_name is null;
update public.dispensaries set legal_name = 'Robinson''S Cannabis Flowers, LLC' where slug = 'robinson-s-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Dank716' where slug = 'dank716-llc-new-ein-92-3339286' and legal_name is null;
update public.dispensaries set legal_name = 'A & P Dispensary Corp' where slug = 'a-and-p-dispensary-corp' and legal_name is null;
update public.dispensaries set legal_name = 'Livelyharvestny LLC' where slug = 'livelyharvestny-llc' and legal_name is null;
update public.dispensaries set legal_name = 'The Coughie Shop Limited Liability Company' where slug = 'the-coughie-shop-limited-liability-company' and legal_name is null;
update public.dispensaries set legal_name = 'The Green Hut, LLC' where slug = 'the-green-hut-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Pure Blossoms LLC' where slug = 'pure-blossoms-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Just A Little Higher LLC' where slug = 'just-a-little-higher-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Authentic 212 LLC' where slug = 'authentic-212-llc' and legal_name is null;
update public.dispensaries set legal_name = '3807 Harlem Cannabis LLC' where slug = 'buffalo-cannabis-outlet' and legal_name is null;
update public.dispensaries set legal_name = 'Sky High Club LLC' where slug = 'sky-high-club-llc' and legal_name is null;
update public.dispensaries set legal_name = 'The Bontemps Firm Retail, LLC' where slug = 'the-bontemps-firm-retail-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Cl Canna Holdings, LLC' where slug = 'cl-canna-holdings-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Of The Earth Canna LLC' where slug = 'otec' and legal_name is null;
update public.dispensaries set legal_name = 'Green Tongue LLC' where slug = 'green-tongue-llc' and legal_name is null;
update public.dispensaries set legal_name = 'No Volume Records LLC' where slug = 'mr-good-vybz' and legal_name is null;
update public.dispensaries set legal_name = 'Summit Canna LLC' where slug = 'conbud' and legal_name is null;
update public.dispensaries set legal_name = 'Premier Earth Corp.' where slug = 'premier-earth-corp' and legal_name is null;
update public.dispensaries set legal_name = 'Wlmc Mainco LLC' where slug = 'the-green-house' and legal_name is null;
update public.dispensaries set legal_name = 'Zai Housing INC.' where slug = 'capital-cannabis' and legal_name is null;
update public.dispensaries set legal_name = 'Cannalicious LLC' where slug = 'cannalicious-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Samjny Holdings LLC' where slug = 'the-flowery' and legal_name is null;
update public.dispensaries set legal_name = 'Cbj Retail LLC' where slug = 'cbj-retail-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Storytellers New York, LLC' where slug = 'bx-buddiez' and legal_name is null;
update public.dispensaries set legal_name = '581 Realty Cld LLC' where slug = 'the-flower-pot' and legal_name is null;
update public.dispensaries set legal_name = 'Bzd Enterprises LLC' where slug = 'bzd-enterprises-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Roc Dispensary And Hydroponics LLC' where slug = 'roc-dispensary-and-hydroponics-llc' and legal_name is null;
update public.dispensaries set legal_name = 'True North Cannabis LLC' where slug = 'true-north-cannabis-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Briar Hill Holdings LLC' where slug = 'briar-hill-holdings-llc' and legal_name is null;
update public.dispensaries set legal_name = 'R&R Remedies LLC' where slug = 'r-and-r-remedies' and legal_name is null;
update public.dispensaries set legal_name = 'Thinc Provisions INC' where slug = 'thinc-provisions-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Tedg LLC' where slug = 'the-emerald-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Southern Tier Cannabis INC.' where slug = 'southern-tier-cannabis-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Upstate Craft Cannabis LLC' where slug = 'upstate-craft-cannabis-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Nughub Ny LLC' where slug = 'nughub-ny-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Fireleaf, LLC' where slug = 'fireleaf-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Nyse3au-Retail INC' where slug = 'silk-road-nyc' and legal_name is null;
update public.dispensaries set legal_name = 'Bourne High LLC' where slug = 'brooklyn-bourne-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Weeds R Us INC' where slug = 'liberty-buds' and legal_name is null;
update public.dispensaries set legal_name = 'October Basics, LLC' where slug = 'october-basics-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Altitude Ny LLC' where slug = 'altitude-ny-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Quality Roots, LLC' where slug = 'quality-roots-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Bud City Cannabis LLC' where slug = 'bud-city-cannabis-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Hf Retail 1 LLC' where slug = 'high-frequency' and legal_name is null;
update public.dispensaries set legal_name = 'High Of Brooklyn LLC' where slug = 'high-of-brooklyn-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Sith Lord Td INC.' where slug = 'sith-lord-td-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Buffalo Cannabis Connect, LLC' where slug = 'buffalo-cannabis-connect-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Wnyc Ii, LLC' where slug = 'tree-head-culture' and legal_name is null;
update public.dispensaries set legal_name = 'Luxus Botanica' where slug = 'luxus-botanica' and legal_name is null;
update public.dispensaries set legal_name = 'The Canna Guy LLC' where slug = 'the-canna-guy-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Newburgh Kush Factory' where slug = 'newburgh-kush-factory' and legal_name is null;
update public.dispensaries set legal_name = 'Wonderland Dispensary Corp' where slug = 'wonderland-dispensary-corp' and legal_name is null;
update public.dispensaries set legal_name = 'Ramon Reyes LLC' where slug = 'ramon-reyes-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Dispo/Bk LLC' where slug = 'dispo-bk-llc' and legal_name is null;
update public.dispensaries set legal_name = 'One Love Cures, LLC' where slug = 'island-vibes-cannabis-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Superfly Dispensary LLC' where slug = 'superfly-dispensary-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Conbud LLC' where slug = 'conbud-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Solo Greenery' where slug = 'solo-greenery' and legal_name is null;
update public.dispensaries set legal_name = 'Hydroman Dispensary' where slug = 'gotham-hudson' and legal_name is null;
update public.dispensaries set legal_name = 'Buffalo Rush Fam Future, LLC' where slug = 'buffalo-rush-fam-future-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Excelsior Cannabis, INC.' where slug = 'silver-cannabis-company' and legal_name is null;
update public.dispensaries set legal_name = 'Free Thinkers LLC' where slug = 'free-thinkers-llc' and legal_name is null;
update public.dispensaries set legal_name = '296 Retail Venture LLC' where slug = '296-retail-venture-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Occ Wny Ventures' where slug = 'star-buds' and legal_name is null;
update public.dispensaries set legal_name = 'Three Cord Ranch LLC' where slug = 'three-cord-cannabis' and legal_name is null;
update public.dispensaries set legal_name = 'Paradise Cannabis LLC' where slug = 'paradise-cannabis-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Mileva LLC' where slug = 'mileva-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Kingston Ny Cannabis LLC' where slug = 'kingston-ny-cannabis-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Bk Exotic Outlet LLC' where slug = 'bk-exotic' and legal_name is null;
update public.dispensaries set legal_name = 'Aja Cannabis 1010 LLC' where slug = 'aja-cannabis-1010-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Caurd Wellness LLC' where slug = 'caurd-wellness-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Canna Life Ny INC.' where slug = 'hii' and legal_name is null;
update public.dispensaries set legal_name = 'Lucky Green Ladies Ny, LLC' where slug = 'lucky-green-ladies' and legal_name is null;
update public.dispensaries set legal_name = 'Vedaleaf LLC' where slug = 'vedaleaf-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Star Life Retail Group LLC' where slug = 'star-life-retail-group-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Green Health, L.L.C.' where slug = 'emerald-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Hand In Bush LLC' where slug = 'hand-in-bush-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Sensi Smoke LLC' where slug = 'bloom-cannabis-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Frenchie Herb LLC' where slug = 'mister-greens' and legal_name is null;
update public.dispensaries set legal_name = 'Salt City Naturals, LLC' where slug = 'salt-city-naturals-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Capri Holdings 2 LLC' where slug = 'budr-cannabis' and legal_name is null;
update public.dispensaries set legal_name = 'Catskill Cannabis Ny LLC' where slug = 'catskill-cannabis-ny-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Cannabliss Recreational Marijuana Dispensary LLC' where slug = 'cannabliss-recreational-marijuana-dispensary-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Patient''S Pharmacy INC.' where slug = 'lifted' and legal_name is null;
update public.dispensaries set legal_name = 'Budbiz LLC' where slug = 'budbiz-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Williamjane Corporation' where slug = 'williamjane' and legal_name is null;
update public.dispensaries set legal_name = 'Savo Group INC' where slug = 'altocanna' and legal_name is null;
update public.dispensaries set legal_name = 'Jeremy Cobin' where slug = 'nautical-blaze-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Cloudfather LLC' where slug = 'flynnstoned-cannabis-company-williamsville' and legal_name is null;
update public.dispensaries set legal_name = 'Monty''S Group Enterprise LLC' where slug = 'high-rollers-cannabis' and legal_name is null;
update public.dispensaries set legal_name = 'Chesterfield Cannabis CO., LLC' where slug = 'chesterfield-cannabis-co-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Misfits Dispensary R3, LLC' where slug = 'not-applicable-at-the-moment' and legal_name is null;
update public.dispensaries set legal_name = 'Florisun LLC' where slug = 'dazed' and legal_name is null;
update public.dispensaries set legal_name = 'Dream Daze LLC' where slug = 'dream-daze-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Canna Life LLC' where slug = 'happy-goat-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Cj Business Ventures LLC' where slug = 'caldwell-cannabis-co' and legal_name is null;
update public.dispensaries set legal_name = 'Down To Earth Canna INC' where slug = 'down-to-earth-canna-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Platinum Leaf LLC' where slug = 'platinum-leaf-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Statis Ny Holdings LLC' where slug = 'statis-ny-holdings-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Blazinup LLC' where slug = 'the-alchemy' and legal_name is null;
update public.dispensaries set legal_name = 'Alyssa M Renko' where slug = 'alyssa-m-renko' and legal_name is null;
update public.dispensaries set legal_name = 'Ny Elite Enterprises 2 INC' where slug = 'ny-elite-cannabis' and legal_name is null;
update public.dispensaries set legal_name = 'Asking Edward, LLC' where slug = 'flynnstoned-cannabis-company-auburn' and legal_name is null;
update public.dispensaries set legal_name = 'Smelly Nelly LLC' where slug = 'the-flowery-2' and legal_name is null;
update public.dispensaries set legal_name = 'Polanco Brothers Corp' where slug = 'polanco-brothers-corp' and legal_name is null;
update public.dispensaries set legal_name = 'Heavenly Garden Ny INC' where slug = 'heavenly-garden-ny-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Buzzsaw Cannabis Company LLC' where slug = 'buzzsaw-cannabis-company' and legal_name is null;
update public.dispensaries set legal_name = 'Juniper Ny LLC' where slug = 'juniper-ny-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Case Managment INC.' where slug = 'case-management' and legal_name is null;
update public.dispensaries set legal_name = 'Xander Legacy, LLC' where slug = 'by-any-other-name' and legal_name is null;
update public.dispensaries set legal_name = 'Rawleaf Enterprises LLC' where slug = 'rawleaf-enterprises-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Royal Buds LLC' where slug = 'royal-buds-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Niyawill LLC' where slug = 'exit-31-exotic' and legal_name is null;
update public.dispensaries set legal_name = 'Herbalwai LLC' where slug = 'herbalwai-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Lotusworks Wellness INC.' where slug = 'lotusworks-wellness-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Ladies & Gentlemen Elevation Headquarters INC.' where slug = 'elevation-headquarters' and legal_name is null;
update public.dispensaries set legal_name = 'A Cannaful Life LLC' where slug = 'a-cannaful-life-llc' and legal_name is null;
update public.dispensaries set legal_name = 'The Goodie Bag, LLC' where slug = 'the-goodie-bag-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Zootiez LLC' where slug = 'zootiez-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Rockaway Moonshot, LLC' where slug = 'rockaway-moonshot-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Ek Green LLC' where slug = 'canterra' and legal_name is null;
update public.dispensaries set legal_name = 'Guardian Wellness LLC' where slug = 'guardian-wellness-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Canna Health And Wellness LLC' where slug = 'canna-health-and-wellness-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Liberty Ny Cannabis, LLC' where slug = 'liberty-ny-cannabis-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Ny Rochester Group, LLC' where slug = 'mango-cannabis' and legal_name is null;
update public.dispensaries set legal_name = 'Cannabis Group Ny, LLC' where slug = 'cannabis-group-ny-llc' and legal_name is null;
update public.dispensaries set legal_name = 'D-Andrews LLC' where slug = 'upstate-cbd' and legal_name is null;
update public.dispensaries set legal_name = 'Washington Place Dispensary LLC' where slug = 'washington-place-dispensary-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Divine Kinnektion LLC' where slug = 'divine-kinnektion-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Chronic Brooklyn LLC' where slug = 'chronic-brooklyn' and legal_name is null;
update public.dispensaries set legal_name = 'Robin Hood Cannabis LLC' where slug = 'dagmar-cannabis' and legal_name is null;
update public.dispensaries set legal_name = 'Green Glee INC' where slug = 'green-glee' and legal_name is null;
update public.dispensaries set legal_name = 'Chronic Bliss LLC' where slug = 'altitude-ithaca' and legal_name is null;
update public.dispensaries set legal_name = 'Fix My Phone INC' where slug = 'oc-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Blue Forest Farms Dispensary LLC' where slug = 'blue-forest-farms-dispensary-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Vaporize, INC.' where slug = 'vaporize-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Actualize Dispensary INC' where slug = 'chelsea-cannabis-co' and legal_name is null;
update public.dispensaries set legal_name = '212partners' where slug = 'stashmaster' and legal_name is null;
update public.dispensaries set legal_name = 'Happy Cork Bedstuy' where slug = 'happy-buds-brooklyn' and legal_name is null;
update public.dispensaries set legal_name = 'Zenzest LLC' where slug = 'zenzest-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Rock Quarry Farms LLC' where slug = 'rock-quarry-farms-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Cannabis Emporium Corp.' where slug = 'hush' and legal_name is null;
update public.dispensaries set legal_name = 'Love Nug, LLC' where slug = 'love-nug-llc' and legal_name is null;
update public.dispensaries set legal_name = 'The Next Chapter Ny LLC' where slug = 'treehouse-cannabis' and legal_name is null;
update public.dispensaries set legal_name = 'Sage Holdco, INC.' where slug = 'sage-holdco-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Cannabis Company Of New York LLC' where slug = 'cannabis-company-of-new-york-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Aroma Farms INC' where slug = 'aroma-farms-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Ashley Capraro LLC' where slug = 'ashley-capraro-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Best Buds Thirteen LLC' where slug = 'best-buds-thirteen-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Enflor LLC' where slug = 'enflor-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Happy Days Dispensary INC.' where slug = 'happy-days-dispensary-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Unbothered Bud, LLC' where slug = 'root-9-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Gmdss' where slug = 'the-travel-agency-downtown-brooklyn' and legal_name is null;
update public.dispensaries set legal_name = 'Lar Memorabilia LLC' where slug = 'lar-memorabilia-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Bloom Brothers Ny, INC.' where slug = 'bloom-brothers' and legal_name is null;
update public.dispensaries set legal_name = 'World Piece, LLC' where slug = 'world-piece-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Strong Island Chronic LLC' where slug = 'strong-strains' and legal_name is null;
update public.dispensaries set legal_name = 'Big Bro Consulting LLC' where slug = 'crush-new-scotland-and-grove-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Calknap INC.' where slug = 'cloud-914' and legal_name is null;
update public.dispensaries set legal_name = 'Yager Farms INC' where slug = 'yager-farms-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Cws Holdings I, LLC' where slug = 'aspire' and legal_name is null;
update public.dispensaries set legal_name = 'Capital District Cannabis & Wellness INC.' where slug = 'capital-district-cannabis-and-wellness-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Catskill Botanicals, LLC' where slug = 'catskill-botanicals' and legal_name is null;
update public.dispensaries set legal_name = 'Trader Li Capital LLC' where slug = 'the-goat-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Token Retail INC' where slug = 'token-retail-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Nnc 2 LLC' where slug = 'nnc-2-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Hop-N-Hemp Tea INC.' where slug = 'hop-n-hemp-tea-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Diamond Dispensary LLC' where slug = 'diamond-dispensary-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Treehouse Upstate Ny, INC' where slug = 'cannabicity' and legal_name is null;
update public.dispensaries set legal_name = 'S & M Unlimited Holdings LLC' where slug = 'the-highend-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Juicy Wellness INC.' where slug = 'juicy-wellness-inc' and legal_name is null;
update public.dispensaries set legal_name = 'L A Ffoca LLC' where slug = 'l-a-ffoca-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Weedkraft LLC' where slug = 'the-flowery-3' and legal_name is null;
update public.dispensaries set legal_name = 'Raven Dispensaries LLC' where slug = 'raven-s-joint' and legal_name is null;
update public.dispensaries set legal_name = 'Windy Hill Wellness 312 LLC' where slug = 'windy-hill-wellness' and legal_name is null;
update public.dispensaries set legal_name = 'Luxe Leaf Boutique LLC' where slug = 'luxe-leaf-boutique-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Official Jjm INC.' where slug = 'official-jjm-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Exotic Farms LLC' where slug = 'exotic-farms-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Herb-Z LLC' where slug = 'herb-z' and legal_name is null;
update public.dispensaries set legal_name = 'Social Equity Caurd Jv LLC' where slug = 'the-cannabis-place' and legal_name is null;
update public.dispensaries set legal_name = 'Kings Raw Property LLC' where slug = 'kings-house-of-fire' and legal_name is null;
update public.dispensaries set legal_name = 'Brownies Dispensary LLC' where slug = 'brownies' and legal_name is null;
update public.dispensaries set legal_name = 'Epic Parlay LLC' where slug = 'say-less' and legal_name is null;
update public.dispensaries set legal_name = 'Blaze 420 LLC' where slug = '202-cannabis-co' and legal_name is null;
update public.dispensaries set legal_name = 'Moore & More, LLC' where slug = 'woodstock-oasis' and legal_name is null;
update public.dispensaries set legal_name = 'Budega Nyc, INC.' where slug = 'budega-nyc' and legal_name is null;
update public.dispensaries set legal_name = 'Inside The Park Dispo LLC' where slug = 'inside-the-park-dispo-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Weedish LLC' where slug = 'weedish-llc' and legal_name is null;
update public.dispensaries set legal_name = '3 - 5 Holdings LLC' where slug = 'the-highly-connected-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Khaar Wellness LLC' where slug = 'leaf-plug' and legal_name is null;
update public.dispensaries set legal_name = 'Eastern Holdings 88 LLC' where slug = 'clouditude-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Cca Buds Syracuse, INC' where slug = 'thrive-syracuse' and legal_name is null;
update public.dispensaries set legal_name = 'Empire State Gallery Holdings, LLC' where slug = 'king-of-budz' and legal_name is null;
update public.dispensaries set legal_name = 'Amsm LLC' where slug = 'amsm-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Jfk Cannabis INC' where slug = 'jfk-cannabis-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Urban Weeds LLC' where slug = 'urban-weeds-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Pramukh 162' where slug = 'pramukh-162' and legal_name is null;
update public.dispensaries set legal_name = 'High Rise Brands LLC' where slug = 'the-hamptons-collective' and legal_name is null;
update public.dispensaries set legal_name = 'Frass Box Cannabis LLC' where slug = 'frass-box-cannabis-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Hybrid Nyc LLC' where slug = 'gotham-williamsburg' and legal_name is null;
update public.dispensaries set legal_name = 'Eruditoherbals LLC' where slug = 'erudito-cannabis-boutique' and legal_name is null;
update public.dispensaries set legal_name = 'Mambo Wellness INC.' where slug = 'mambo-wellness-inc' and legal_name is null;
update public.dispensaries set legal_name = 'No Name Cannabis Company, LLC' where slug = 'no-name-cannabis-company-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Kingston Cannabis LLC' where slug = 'kingston-cannabis-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Up State Sports Cards LLC' where slug = 'the-bakery' and legal_name is null;
update public.dispensaries set legal_name = 'Root 13, LLC' where slug = 'good-daze-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Bloomlee LLC' where slug = 'alta-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Dai Ma LLC' where slug = 'lighthouse-cannabis' and legal_name is null;
update public.dispensaries set legal_name = 'Herbal I.Q. INC.' where slug = 'herbal-i-q' and legal_name is null;
update public.dispensaries set legal_name = 'Healthy Choice Seaview LLC' where slug = 'healthy-choice-seaview-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Dosha Farms LLC' where slug = 'dosha-farms' and legal_name is null;
update public.dispensaries set legal_name = 'Fufa LLC' where slug = 'fufa-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Yesca, LLC' where slug = 'cannabis-depot' and legal_name is null;
update public.dispensaries set legal_name = 'Two Buds Enterprise, INC.' where slug = 'two-buds-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Lake Goat LLC' where slug = 'lake-goat-llc' and legal_name is null;
update public.dispensaries set legal_name = '14707 45th LLC' where slug = '14707-45th-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Sps Enterprises, LLC' where slug = 'tridentru' and legal_name is null;
update public.dispensaries set legal_name = 'Veteran Warriors Of Wny, LLC' where slug = 'the-natural-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Flynnstoned Corporation' where slug = 'flynnstoned' and legal_name is null;
update public.dispensaries set legal_name = 'Big City Flavors LLC' where slug = 'big-city-flavors' and legal_name is null;
update public.dispensaries set legal_name = 'Windyhill 312 LLC' where slug = 'windy-hill-wellness-glens-falls' and legal_name is null;
update public.dispensaries set legal_name = 'The Cannabis Spot INC.' where slug = 'the-cannabis-spot-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Art Of Flower Farm & Dispensary LLC' where slug = 'art-of-flower-farm-and-dispensary-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Mzdz Corp' where slug = 'mzdz-corp' and legal_name is null;
update public.dispensaries set legal_name = 'Slg-Db LLC' where slug = 'pryzm' and legal_name is null;
update public.dispensaries set legal_name = 'Grape Stomper LLC' where slug = 'grape-stomper-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Excite Unlimited LLC' where slug = 'excite-unlimited-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Sunwalker Farms, INC.' where slug = 'sunwalker-farms-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Command Cannabis Dispensary INC.' where slug = 'command-cannabis-dispensary-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Notorious Tree Ny LLC' where slug = 'notorious-tree-ny-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Native Haze Cannabis CO. LLC' where slug = 'native-haze-cannabis-co-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Buffalo Cannabis Store LLC' where slug = 'buffalo-cannabis-store-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Cebede, LLC' where slug = 'cebede-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Animo Cbd LLC' where slug = 'animo-cbd-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Village One Stop Smoke Shop INC.' where slug = 'village-one-stop-smoke-shop-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Cloud 9 Evolution LLC' where slug = 'cloud-9-evolution-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Best Of Harlem Grade LLC' where slug = 'gotham-chelsea' and legal_name is null;
update public.dispensaries set legal_name = 'East Branch Holdings LLC' where slug = 'east-branch-holdings-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Stay Blessed LLC' where slug = 'stay-blessed-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Lotus Dispensary LLC' where slug = 'high-road' and legal_name is null;
update public.dispensaries set legal_name = 'Dansville Dispensary Corporation' where slug = 'dansville-dispensary-corporation' and legal_name is null;
update public.dispensaries set legal_name = 'Union Chill Cannabis Ny LLC' where slug = 'union-chill-cannabis-ny-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Supply Design LLC' where slug = 'supply-design-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Grow 716 INC.' where slug = 'grow-716-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Cb Budco LLC' where slug = 'cb-budco-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Greens Greenery LLC' where slug = 'greens-greenery' and legal_name is null;
update public.dispensaries set legal_name = 'Buddeez LLC' where slug = 'buddeez-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Mammoth Business, LLC' where slug = 'mammoth-cannabis' and legal_name is null;
update public.dispensaries set legal_name = '1650 Crane Street Dispensary LLC' where slug = '1650-crane-street-dispensary-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Luxe Oasis, LLC' where slug = 'renaissant-nyc' and legal_name is null;
update public.dispensaries set legal_name = 'Gone Tiki LLC' where slug = 'high-tide' and legal_name is null;
update public.dispensaries set legal_name = 'Goldleaf Cannabis LLC' where slug = 'goldleaf-cannabis' and legal_name is null;
update public.dispensaries set legal_name = '201 East 30th Corp.' where slug = 'smiley-exotics' and legal_name is null;
update public.dispensaries set legal_name = 'Flx Canna Cart LLC' where slug = 'good-life-collective-fingerlakes' and legal_name is null;
update public.dispensaries set legal_name = 'R&R Cannabis LLC' where slug = 'r-and-r-cannabis-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Canna Buddha Corp' where slug = 'canna-buddha-corp' and legal_name is null;
update public.dispensaries set legal_name = 'Askone''S LLC' where slug = 'skones-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'A Classy Joint Cannabis, LLC' where slug = 'a-classy-joint-cannabis-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Bodega Dreams LLC' where slug = 'flynnstoned-cannabis-company' and legal_name is null;
update public.dispensaries set legal_name = 'Caurd Brooklyn Corp' where slug = 'misha-s-flower-shop' and legal_name is null;
update public.dispensaries set legal_name = 'Luke Cloud, INC.' where slug = 'bronx-joint' and legal_name is null;
update public.dispensaries set legal_name = 'Domenick Dicostanzo LLC' where slug = 'oz-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Flower Power Nyc Corp.' where slug = 'flower-power-dispensers' and legal_name is null;
update public.dispensaries set legal_name = 'Cnbs27 INC.' where slug = 'cnbs27-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Flower City Shop LLC' where slug = 'weedndeed' and legal_name is null;
update public.dispensaries set legal_name = 'Bcpsi Enterprises LLC' where slug = 'highstone' and legal_name is null;
update public.dispensaries set legal_name = 'Hudson Park Agency LLC' where slug = 'hudson-park-agency-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Innocence Cannabis LLC' where slug = 'innocence-cannabis' and legal_name is null;
update public.dispensaries set legal_name = 'Nsh LLC' where slug = 'nsh-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Seven Amazing Kids LLC' where slug = 'celestial-herbs' and legal_name is null;
update public.dispensaries set legal_name = 'Caffiend LLC' where slug = 'caffiend-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Level Up Nyc Corp.' where slug = 'nyc-bud-midtown' and legal_name is null;
update public.dispensaries set legal_name = 'Lowdest LLC' where slug = 'high-dankery' and legal_name is null;
update public.dispensaries set legal_name = 'Greenleaf Cannabis LLC' where slug = 'greenleaf-cannabis-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Kaur Consulting LLC' where slug = 'kaur-consulting-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Custom Cannabis Solutions LLC' where slug = 'cannabis-corner' and legal_name is null;
update public.dispensaries set legal_name = 'Taliaferro Farm Store LLC' where slug = 'lady-green-sleeves' and legal_name is null;
update public.dispensaries set legal_name = 'Twisted Vibration LLC' where slug = 'twisted-vibration-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Sessco Corp.' where slug = 'sessco-corp' and legal_name is null;
update public.dispensaries set legal_name = 'One Life Cannabis LLC' where slug = 'just-breathe-syracuse' and legal_name is null;
update public.dispensaries set legal_name = 'Misty Bleu Farm LLC' where slug = 'misty-bleu-farm-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Upstate Edge, LLC' where slug = 'upstate-edge-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Big Gas Dispensary' where slug = 'big-gas-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Joe''S Buds, LLC' where slug = 'joe-s-buds-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Plant Meets Public LLC' where slug = 'plant-meets-public-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Wappingers Cannabis LLC' where slug = 'wappingers-cannabis-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Indoor Treez Corp.' where slug = 'indoor-treez-corp' and legal_name is null;
update public.dispensaries set legal_name = 'Green Philosophy 716 INC.' where slug = 'green-philosophy-716-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Garden Bliss LLC' where slug = 'garden-bliss-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Igal Consulting, INC.' where slug = 'lease-from-me' and legal_name is null;
update public.dispensaries set legal_name = 'Gratitude Buds Dispensary LLC' where slug = 'fishkill-cannabis' and legal_name is null;
update public.dispensaries set legal_name = 'Amsterdam Cannabis, INC.' where slug = 'amsterdam-cannabis-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Ragtime Newstand And Lotto, INC.' where slug = 'ragtime-newstand-and-lotto-inc' and legal_name is null;
update public.dispensaries set legal_name = '960 Bloomingdale Road LLC' where slug = '960-bloomingdale-road-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Crown And Gavel LLC' where slug = 'crown-and-gavel-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Aa 301 W. 45th St INC.' where slug = 'aa-301-w-45th-st-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Finger Lakes Hydro LLC' where slug = '6-point-cannabis' and legal_name is null;
update public.dispensaries set legal_name = 'Toptierco, LLC' where slug = 'serenity-now-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Bud Brothers And Sisters LLC' where slug = 'bud-brothers-and-sisters-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Astro Management, INC.' where slug = 'astro-management-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Erie County Cannabis LLC' where slug = 'erie-county-cannabis-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Late Bloomers Nyc LLC' where slug = 'late-bloomers-nyc-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Back Home Farm LLC' where slug = 'back-home-cannabis-co' and legal_name is null;
update public.dispensaries set legal_name = 'Michael Schweikowsky' where slug = 'the-cannabis-store' and legal_name is null;
update public.dispensaries set legal_name = 'L.O.R.D.S. LLC' where slug = 'housing-works-cannabis-co' and legal_name is null;
update public.dispensaries set legal_name = 'Jwa Dh INC' where slug = 'jwa-dh-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Seneca Cann LLC' where slug = 'seneca-cannabis' and legal_name is null;
update public.dispensaries set legal_name = 'Qube Usa LLC' where slug = 'qube' and legal_name is null;
update public.dispensaries set legal_name = 'The Hootch LLC' where slug = 'the-hootch-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Hoosick Dispensary LLC' where slug = 'hoosick-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Dynasty Commodities, INC.' where slug = 'paint-puff-n-peace' and legal_name is null;
update public.dispensaries set legal_name = 'Gaea Design And Management LLC' where slug = 'gaea-s-garden' and legal_name is null;
update public.dispensaries set legal_name = 'Grass Roots Wellness Ny LLC' where slug = 'grass-roots-wellness-ny-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Midnight Moon Corp' where slug = 'midnight-moon-corp' and legal_name is null;
update public.dispensaries set legal_name = 'Devil''S Lettuce LLC' where slug = 'devil-s-lettuce-llc' and legal_name is null;
update public.dispensaries set legal_name = 'I Bud You Ny, INC' where slug = 'i-bud-you-ny-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Black River Supply Company, LLC' where slug = 'black-river-supply-company-llc' and legal_name is null;
update public.dispensaries set legal_name = 'The Herb Cave, LLC' where slug = 'the-herb-cave-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Bayside Supply INC' where slug = 'silky-strain' and legal_name is null;
update public.dispensaries set legal_name = 'Electric City Cannabis CO, LLC' where slug = 'electric-city-cannabis-co-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Terrapin Greens' where slug = 'terrapin-greens' and legal_name is null;
update public.dispensaries set legal_name = 'Grub Bud LLC' where slug = 'grub-bud-llc' and legal_name is null;
update public.dispensaries set legal_name = '2 Forest Park Lane LLC' where slug = 'charlie-fox' and legal_name is null;
update public.dispensaries set legal_name = '100 North 3rd Ltd' where slug = '7-leaf-clover' and legal_name is null;
update public.dispensaries set legal_name = 'Tj''S Cannabis Corp.' where slug = 'tj-s-cannabis-corp' and legal_name is null;
update public.dispensaries set legal_name = 'Kbat Enterprises INC.' where slug = 'kbat-enterprises-inc' and legal_name is null;
update public.dispensaries set legal_name = 'My Bud 420 INC.' where slug = 'my-bud-420-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Nickel City Green, LLC' where slug = 'nickel-city-green-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Lisa Birnbaum Personal Training, LLC' where slug = 'lisa-birnbaum-personal-training-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Smoking Scholars LLC' where slug = 'smoking-scholars-llc' and legal_name is null;
update public.dispensaries set legal_name = '463 Station, INC.' where slug = 'the-station-beacon' and legal_name is null;
update public.dispensaries set legal_name = 'Fumi Dispensary LLC' where slug = 'fumi-dispensary-llc' and legal_name is null;
update public.dispensaries set legal_name = 'East Leaf LLC' where slug = 'east-leaf-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Egrh LLC' where slug = 'riverbend-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Central Apothecary LLC' where slug = 'lucky-dog-420' and legal_name is null;
update public.dispensaries set legal_name = 'Munchie''S Dispensary Ny LLC' where slug = 'munchie-s-dispensary-ny-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Hornbill INC.' where slug = 'hornbill-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Small Leaf 79 LLC' where slug = 'small-leaf-79-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Atmospheric Hues LLC' where slug = 'white-atmoss' and legal_name is null;
update public.dispensaries set legal_name = 'Best Budz Cannabis CO. LLC' where slug = 'best-budz-cannabis-co-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Apf Syndicate Corp' where slug = 'the-flowery-new-york' and legal_name is null;
update public.dispensaries set legal_name = 'Atnc INC' where slug = 'atnc-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Classy Canna, LLC' where slug = 'classy-canna-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Ny Cannabis Dispensary LLC' where slug = 'ny-cannabis-dispensary-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Tap Root Family LLC' where slug = 'tap-root-family-llc' and legal_name is null;
update public.dispensaries set legal_name = 'High Peaks Canna INC.' where slug = 'high-peaks-canna-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Loudpack Exotics LLC' where slug = 'loudpack-exotics' and legal_name is null;
update public.dispensaries set legal_name = 'Addie A Jenne' where slug = 'high-falls-garden' and legal_name is null;
update public.dispensaries set legal_name = '58 Gp Avenue LLC' where slug = '58-gp-avenue-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Kiki Buddz Corp.' where slug = 'kiki-buddz-corp' and legal_name is null;
update public.dispensaries set legal_name = 'Green Klub INC.' where slug = 'green-klub-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Tree Market Ny LLC' where slug = 'tree-market-ny-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Jjsk INC.' where slug = 'jjsk-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Pure Wellness Dispensary LLC' where slug = 'pure-wellness-dispensary-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Nipapoa LLC' where slug = 'nipapoa-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Canary Cannabis CO LLC' where slug = 'ether-buffalo' and legal_name is null;
update public.dispensaries set legal_name = 'Bme Holdings Of Ny LLC' where slug = 'yeti-greenery' and legal_name is null;
update public.dispensaries set legal_name = 'Smokey Paradise LLC' where slug = 'smokey-paradise-llc' and legal_name is null;
update public.dispensaries set legal_name = 'The Cannabis Vault LLC' where slug = 'the-cannabis-vault-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Westage 7, LLC' where slug = 'farmers-choice-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Happy Dayz Cannabis Dispensary' where slug = 'happy-dayz-cannabis-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Leafy Nyc Ii LLC' where slug = 'leafy-nyc-ii-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Organic Relief Leaf, LLC' where slug = 'g-spot-nyc' and legal_name is null;
update public.dispensaries set legal_name = 'Air City Cannabis LLC' where slug = 'air-city-cannabis-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Strain Stars LLC' where slug = 'strain-stars' and legal_name is null;
update public.dispensaries set legal_name = 'Beechnut Ridge Enterprises LLC' where slug = 'the-grass-hole-cannabis' and legal_name is null;
update public.dispensaries set legal_name = 'Jse 26 Corp' where slug = 'jse-26-corp' and legal_name is null;
update public.dispensaries set legal_name = 'Nextgen Endeavors, LLC' where slug = 'nextgen-endeavors-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Cannabliss Recreational LLC' where slug = 'cannabliss-recreational-llc' and legal_name is null;
update public.dispensaries set legal_name = 'T & C Distribution LLC' where slug = 'stoops-nyc' and legal_name is null;
update public.dispensaries set legal_name = 'Mj''S Retail LLC' where slug = 'mj-s-retail-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Evergreen Retail 1, LLC' where slug = 'evergreen-retail' and legal_name is null;
update public.dispensaries set legal_name = 'Pike & Griff LLC' where slug = 'pike-and-griff-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Freedom 35 Cannabis Company LLC' where slug = 'the-mellow-moose' and legal_name is null;
update public.dispensaries set legal_name = 'Jackpot 420 LLC' where slug = 'jackpot-420-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Afi & Associates Group LLC' where slug = 'afi-and-associates-group-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Nc Accident Reports LLC' where slug = 'elevate-soho-cannabis' and legal_name is null;
update public.dispensaries set legal_name = 'Amber Jane LLC' where slug = 'amber-jane' and legal_name is null;
update public.dispensaries set legal_name = 'Nycecity LLC' where slug = 'society-house' and legal_name is null;
update public.dispensaries set legal_name = 'Ny Retail 5 INC.' where slug = 'ny-retail-5-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Trends Dispensaries LLC' where slug = 'trends-dispensaries-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Dutchess Roots LLC' where slug = 'dutchess-roots-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Sanat Cards & Gifts INC' where slug = 'sanat-cards-and-gifts-inc' and legal_name is null;
update public.dispensaries set legal_name = 'The Higher Company LLC' where slug = 'the-higher-co' and legal_name is null;
update public.dispensaries set legal_name = 'Seaweed Rbny' where slug = 'seaweed-rbny' and legal_name is null;
update public.dispensaries set legal_name = 'Bud & Honey Dispensary INC.' where slug = 'bud-and-honey-dispensary-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Mighty Lucky INC.' where slug = 'mighty-lucky-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Half Island Flavors LLC' where slug = 'sesh-nyc' and legal_name is null;
update public.dispensaries set legal_name = 'Beast Coast Group LLC' where slug = 'beast-coast-group-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Green Leaf Wellness CO. LLC' where slug = 'green-leaf-wellness-co-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Corner House, LLC' where slug = 'corner-house-llc' and legal_name is null;
update public.dispensaries set legal_name = '716 Mj LLC' where slug = 'forever-4-20' and legal_name is null;
update public.dispensaries set legal_name = 'Better States LLC' where slug = 'flower-daddy' and legal_name is null;
update public.dispensaries set legal_name = 'The Herbal Care Thc LLC' where slug = 'the-herbal-care-thc-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Mill Lane Provisions, LLC' where slug = 'mill-lane-provisions-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Mank LLC' where slug = 'zenzo' and legal_name is null;
update public.dispensaries set legal_name = 'Best Buds Of New York, INC.' where slug = 'best-buds-of-new-york-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Happy Tree LLC' where slug = 'happy-tree-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Jungle Kingdom Flower Company LLC' where slug = 'jungle-kingdom-flower-company-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Black Market Canna CO LLC' where slug = 'black-market-canna-co-llc' and legal_name is null;
update public.dispensaries set legal_name = 'The Weed Shoppe INC.' where slug = 'the-weed-shoppe-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Green Goat Gardens, LLC' where slug = 'green-goat-gardens-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Brooklyn Organic Buds LLC' where slug = 'brooklyn-organic-buds-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Erietreehouse Corporation' where slug = 'diamond-tree-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'M&J Genesis INC' where slug = 'leafy-peaks' and legal_name is null;
update public.dispensaries set legal_name = 'Buzzy Ny, LLC' where slug = 'buzzy-ny-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Dark Horse 2 Corp' where slug = 'dark-horse' and legal_name is null;
update public.dispensaries set legal_name = 'Ddmm Dispensary LLC' where slug = 'ddmm-dispensary-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Bleu Leaf Dispensary INC.' where slug = 'bleu-leaf-dispensary-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Nuna Harvest LLC' where slug = 'nuna-harvest-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Valley Greens Ltd.' where slug = 'valley-greens-ltd' and legal_name is null;
update public.dispensaries set legal_name = 'On Point Cannabis, INC.' where slug = 'just-breathe' and legal_name is null;
update public.dispensaries set legal_name = 'Kushklub Ny LLC' where slug = 'kushklub-ny-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Herbhub LLC' where slug = 'herbhub-llc' and legal_name is null;
update public.dispensaries set legal_name = '4081 Industries, LLC' where slug = 'transcend-wellness-products-and-services' and legal_name is null;
update public.dispensaries set legal_name = 'Richard G Robinson Iii' where slug = 'liquid-monkey' and legal_name is null;
update public.dispensaries set legal_name = 'Yk Botanicals LLC' where slug = 'greene-street-cannabis-co' and legal_name is null;
update public.dispensaries set legal_name = 'Cannaspace INC.' where slug = 'cannaspace-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Nldispo' where slug = 'northern-lights-ny' and legal_name is null;
update public.dispensaries set legal_name = 'Evexia Therapeutics LLC' where slug = 'evexia-cannabis' and legal_name is null;
update public.dispensaries set legal_name = 'Disco Herbatory LLC' where slug = 'disco-herbatory-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Green Witch Dispensary LLC' where slug = 'green-witch-dispensary-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Green Sun INC.' where slug = 'hibernica' and legal_name is null;
update public.dispensaries set legal_name = 'High Society Dispensary LLC' where slug = 'high-society-dispensary-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Cat Rock Caurd LLC' where slug = 'leafology-cannabis-company' and legal_name is null;
update public.dispensaries set legal_name = 'Medablue, LLC' where slug = 'green-genius-nyc' and legal_name is null;
update public.dispensaries set legal_name = 'Puro Vita Enterprises INC.' where slug = 'puro-vita-enterprises-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Hold Up Roll Up, LLC' where slug = 'hold-up-roll-up-llc' and legal_name is null;
update public.dispensaries set legal_name = '82-J LLC' where slug = '82-j-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Fabers Arcade INC.' where slug = 'bad-maryjane' and legal_name is null;
update public.dispensaries set legal_name = 'Westchester Harvesting Company LLC' where slug = 'the-purple-owl-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Coronado LLC' where slug = 'mary-janes-a-legacy-2-legal-dispensary' and legal_name is null;
update public.dispensaries set legal_name = 'Vladimir Bautista, LLC' where slug = 'happy-munkey' and legal_name is null;
update public.dispensaries set legal_name = 'Brown Budda New York LLC' where slug = 'brown-budda-new-york' and legal_name is null;
update public.dispensaries set legal_name = 'Bazzjat Retail INC' where slug = 'bazzjat-retail-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Elivate Ny LLC' where slug = 'elevate-cannabis' and legal_name is null;
update public.dispensaries set legal_name = 'Dnp-Y INC' where slug = 'freshly-baked-nyc' and legal_name is null;
update public.dispensaries set legal_name = 'Royal Blend Dispensary LLC' where slug = 'royal-blend-dispensary-llc' and legal_name is null;
update public.dispensaries set legal_name = 'The Weed Spot LLC' where slug = 'the-weed-spot-llc' and legal_name is null;
update public.dispensaries set legal_name = '1106 Rebecca St Limited Liability Company' where slug = 'herbology-brooklyn' and legal_name is null;
update public.dispensaries set legal_name = 'Humble County LLC' where slug = '420-bliss' and legal_name is null;
update public.dispensaries set legal_name = 'Grow Together LLC' where slug = 'grow-together' and legal_name is null;
update public.dispensaries set legal_name = 'Gotham Caurd LLC' where slug = 'gotham-bowery' and legal_name is null;
update public.dispensaries set legal_name = 'P. Nuggs LLC' where slug = 'p-nuggs-llc' and legal_name is null;
update public.dispensaries set legal_name = 'Are We Good Enterprises INC.' where slug = 'are-we-good-enterprises-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Designs By Pyramid, INC.' where slug = 'sacred-bloom' and legal_name is null;
update public.dispensaries set legal_name = 'Badu Management Corp' where slug = 'higher-tolerance' and legal_name is null;
update public.dispensaries set legal_name = 'Smacked LLC' where slug = 'smacked-llc' and legal_name is null;
update public.dispensaries set legal_name = 'New York City Cannabis Exchange Corp' where slug = 'nycce' and legal_name is null;
update public.dispensaries set legal_name = 'Mj Dispensary LLC' where slug = 'mj-dispensary-llc' and legal_name is null;
update public.dispensaries set legal_name = '7 Point Dispensary INC.' where slug = '7-point-dispensary-inc' and legal_name is null;
update public.dispensaries set legal_name = 'Kush Culture Industry LLC' where slug = 'terp-bros' and legal_name is null;
