-- Seed: real licensed cannabis retailers.
-- Generated by scripts/import-la-dispensaries.mjs from C:\Users\jetni\AppData\Local\Temp/ar-licenses-geo2.csv
-- Source: Arkansas Cannabis Industry Association directory (manually transcribed 2026-07-01, organized by the state's 8 official dispensary zones; geocoded via US Census batch geocoder). Public record / attribution.
-- Filter: all cities, active retailers + microbusiness + non-storefront.
-- Records: 30
insert into public.dispensaries
  (name, slug, address, city, state, zip, phone, email, website, license_number,
   is_medical, is_recreational, is_delivery, is_pickup, location, status)
values
  ('The Hill', 'the-hill-fayetteville', '2733 N. Mcconnell Ave', 'Fayetteville', 'AR', null, '800-266-9057', null, null, 'AR-ABC-001', true, false, false, true, 'SRID=4326;POINT(-94.180589114681 36.102178559813)'::geography, 'active'),
  ('Purspirit Cannabis CO.', 'purspirit-cannabis-co', '3390 Mlk Blvd', 'Fayetteville', 'AR', null, '479-957-1973', null, null, 'AR-ABC-002', true, false, false, true, 'SRID=4326;POINT(-94.207668730279 36.050680533628)'::geography, 'active'),
  ('The Source', 'the-source', '4505 W. Poplar St', 'Rogers', 'AR', '72756', '479-339-9333', null, null, 'AR-ABC-003', true, false, false, true, 'SRID=4326;POINT(-94.1797780743 36.332078776178)'::geography, 'active'),
  ('The Releaf Center', 'the-releaf-center', '9400 Mcnelly Rd', 'Bentonville', 'AR', null, '479-488-2071', null, null, 'AR-ABC-004', true, false, false, true, 'SRID=4326;POINT(-94.170802936625 36.450046916005)'::geography, 'active'),
  ('Osage Creek Dispensary', 'osage-creek-dispensary', '101 E Van Buren', 'Eureka Springs', 'AR', '72632', '479-431-4897', null, null, 'AR-ABC-005', true, false, false, true, 'SRID=4326;POINT(-93.746934632905 36.3989293415)'::geography, 'active'),
  ('Fiddler''s Green Dispensary', 'fiddler-s-green-dispensary', '16150 Highway 9', 'Mountain View', 'AR', null, '870-269-8600', null, null, 'AR-ABC-006', true, false, false, true, 'SRID=4326;POINT(-92.135355750018 35.837271964344)'::geography, 'active'),
  ('Plant Family Therapeutics', 'plant-family-therapeutics', '5172 Hwy 62 E', 'Mountain Home', 'AR', null, '870-709-0800', null, null, 'AR-ABC-007', true, false, false, true, 'SRID=4326;POINT(-92.306154971717 36.373898743598)'::geography, 'active'),
  ('Arkansas Natural Products', 'arkansas-natural-products', '1303 Hwy 65 N', 'Clinton', 'AR', null, '501-386-3166', null, null, 'AR-ABC-008', true, false, false, true, 'SRID=4326;POINT(-92.451900426579 35.576204201985)'::geography, 'active'),
  ('Greenlight West Memphis', 'greenlight-west-memphis', '3600 N Service Rd', 'West Memphis', 'AR', '72301', '870-497-2175', null, null, 'AR-ABC-010', true, false, false, true, 'SRID=4326;POINT(-90.143486680842 35.152905806834)'::geography, 'active'),
  ('Crop', 'crop', '2929 S Caraway Rd', 'Jonesboro', 'AR', '72401', '870-336-2767', null, null, 'AR-ABC-014', true, false, false, true, 'SRID=4326;POINT(-90.678184189158 35.810576929169)'::geography, 'active'),
  ('The Greenery', 'the-greenery-fort-smith', '4520 Phoenix Ave', 'Fort Smith', 'AR', '72908', '479-551-2235', null, null, 'AR-ABC-015', true, false, false, true, 'SRID=4326;POINT(-94.383295639879 35.338064643383)'::geography, 'active'),
  ('420 Dispensary', '420-dispensary', '3506 South Arkansas Ave', 'Russellville', 'AR', null, '479-498-4200', null, null, 'AR-ABC-017', true, false, false, true, 'SRID=4326;POINT(-93.139259860716 35.242807498626)'::geography, 'active'),
  ('Enlightened Dispensary - Clarksville', 'enlightened-dispensary-clarksville', '131 Massengale Rd', 'Clarksville', 'AR', '72830', '479-358-7575', null, null, 'AR-ABC-018', true, false, false, true, 'SRID=4326;POINT(-93.52192041356 35.462402366147)'::geography, 'active'),
  ('Good Day Farm Van Buren', 'good-day-farm-van-buren', '1705 Fayetteville Rd', 'Van Buren', 'AR', '72956', '479-460-4125', null, null, 'AR-ABC-019', true, false, false, true, 'SRID=4326;POINT(-94.356592061098 35.460168041738)'::geography, 'active'),
  ('Harvest', 'harvest-conway', '1200 Thomas G Wilson', 'Conway', 'AR', null, '501-504-6065', null, null, 'AR-ABC-020', true, false, false, true, 'SRID=4326;POINT(-92.41113568166 35.062169089828)'::geography, 'active'),
  ('Greenlight Little Rock', 'greenlight-little-rock', '7303 Kanis Rd', 'Little Rock', 'AR', null, '501-236-6906', null, null, 'AR-ABC-021', true, false, false, true, 'SRID=4326;POINT(-92.355965170616 34.741856060085)'::geography, 'active'),
  ('Berner''s By Good Day Farm', 'berner-s-by-good-day-farm', '11600 Chenal Pkwy', 'Little Rock', 'AR', '72211', '501-441-0944', null, null, 'AR-ABC-022', true, false, false, true, 'SRID=4326;POINT(-92.407616408144 34.749302658125)'::geography, 'active'),
  ('Natural Relief Dispensary', 'natural-relief-dispensary', '3107 East Kiehl Ave', 'Sherwood', 'AR', null, '501-487-6045', null, null, 'AR-ABC-023', true, false, false, true, 'SRID=4326;POINT(-92.199533242609 34.832411165879)'::geography, 'active'),
  ('Suite 443', 'suite-443', '4893 Malvern Ave', 'Hot Springs', 'AR', null, '501-262-9333', null, null, 'AR-ABC-024', true, false, false, true, 'SRID=4326;POINT(-92.980829900054 34.469380435176)'::geography, 'active'),
  ('Green Springs Medical', 'green-springs-medical', '309 Seneca St', 'Hot Springs', 'AR', null, '501-207-0420', null, null, 'AR-ABC-025', true, false, false, true, 'SRID=4326;POINT(-93.048635037486 34.476055240858)'::geography, 'active'),
  ('Native Green Wellness Center', 'native-green-wellness-center', '26225 Highway 167', 'Hensley', 'AR', null, '501-993-0617', null, null, 'AR-ABC-026', true, false, false, true, 'SRID=4326;POINT(-92.343019459074 34.513306984246)'::geography, 'active'),
  ('Custom Cannabis', 'custom-cannabis', '10200 Hwy 5', 'Alexander', 'AR', null, '501-213-0115', null, null, 'AR-ABC-027', true, false, false, true, 'SRID=4326;POINT(-92.44619960556 34.646163068023)'::geography, 'active'),
  ('High Bank Cannabis CO.', 'high-bank-cannabis-co', '525 Mallard Loop', 'Pine Bluff', 'AR', '71603', '870-568-0420', null, null, 'AR-ABC-028', true, false, false, true, 'SRID=4326;POINT(-92.007544865646 34.175428129401)'::geography, 'active'),
  ('Greenlight Dispensary', 'greenlight-dispensary', '2000 Mlk Jr Dr', 'Helena', 'AR', '72342', '870-714-6119', null, null, 'AR-ABC-029', true, false, false, true, 'SRID=4326;POINT(-90.63481470245 34.517451278995)'::geography, 'active'),
  ('Hash & CO.', 'hash-and-co', '110 Girder Field Ladd Rd', 'Pine Bluff', 'AR', '71601', '870-663-0900', null, null, 'AR-ABC-030', true, false, false, true, 'SRID=4326;POINT(-91.957272504522 34.19497488375)'::geography, 'active'),
  ('Good Day Farm Monticello', 'good-day-farm-monticello', '329 Us-425', 'Monticello', 'AR', '71655', '870-412-1244', null, null, 'AR-ABC-031', true, false, false, true, 'SRID=4326;POINT(-91.801883122311 33.634076891756)'::geography, 'active'),
  ('Zen Leaf Dispensary', 'zen-leaf-dispensary', '3213 North West Ave', 'El Dorado', 'AR', '71730', '870-229-1453', null, null, 'AR-ABC-033', true, false, false, true, 'SRID=4326;POINT(-92.664130652868 33.246642851291)'::geography, 'active'),
  ('Superfarm Texarkana', 'superfarm-texarkana', '410 Realtor Ave', 'Texarkana', 'AR', '71854', '870-621-2044', null, null, 'AR-ABC-034', true, false, false, true, 'SRID=4326;POINT(-94.039110210719 33.469757715916)'::geography, 'active'),
  ('Good Day Farm Texarkana', 'good-day-farm-texarkana', '4423 East Broad St', 'Texarkana', 'AR', null, '870-330-4951', null, null, 'AR-ABC-035', true, false, false, true, 'SRID=4326;POINT(-93.992111681772 33.464298611006)'::geography, 'active'),
  ('Enlightened Dispensary - Arkadelphia', 'enlightened-dispensary-arkadelphia', '192 Valley St', 'Caddo Valley', 'AR', '71923', '501-432-4200', null, null, 'AR-ABC-036', true, false, false, true, 'SRID=4326;POINT(-93.072525474569 34.189781359679)'::geography, 'active')
on conflict (slug) do nothing;
