-- Seed: real licensed cannabis retailers.
-- Generated by scripts/import-la-dispensaries.mjs from C:\Users\jetni\AppData\Local\Temp/la-licenses-geo.csv
-- Source: Louisiana Dept. of Health (official medical-marijuana page, manually transcribed 2026-07-01; geocoded via US Census batch geocoder). Public record / attribution.
-- Filter: all cities, active retailers + microbusiness + non-storefront.
-- Records: 22
insert into public.dispensaries
  (name, slug, address, city, state, zip, phone, email, website, license_number,
   is_medical, is_recreational, is_delivery, is_pickup, location, status)
values
  ('H & W Acquisition Company', 'h-and-w-acquisition-company', '1667 Tchoupitoulas Blvd., Suite B', 'New Orleans', 'LA', '70130', '504-301-2363', null, null, 'LA-LDH-001', true, false, false, true, 'SRID=4326;POINT(-90.066674362239 29.929366733589)'::geography, 'active'),
  ('H & W Acquisition Company - Metairie', 'h-and-w-acquisition-company-metairie', '5055 Veterans Memorial Blvd.', 'Metairie', 'LA', '70006', '504-301-2363', null, null, 'LA-LDH-002', true, false, false, true, 'SRID=4326;POINT(-90.196010900244 30.006126563834)'::geography, 'active'),
  ('Crescent City Therapeutics', 'crescent-city-therapeutics', '100 W. Airline Hwy', 'Kenner', 'LA', '70062', '504-800-6420', null, null, 'LA-LDH-003', true, false, false, true, 'SRID=4326;POINT(-90.277089154284 29.980254293856)'::geography, 'active'),
  ('Crescent City Therapeutics - New Orleans', 'crescent-city-therapeutics-new-orleans', '1407 S. Carrollton Avenue', 'New Orleans', 'LA', '70118', '504-554-0003', null, null, 'LA-LDH-004', true, false, false, true, 'SRID=4326;POINT(-90.127982750779 29.948672230136)'::geography, 'active'),
  ('Capitol Wellness Solutions', 'capitol-wellness-solutions', '8037 Picardy Avenue', 'Baton Rouge', 'LA', '70809', '225-800-9420', null, null, 'LA-LDH-005', true, false, false, true, 'SRID=4326;POINT(-91.105726263528 30.397344156687)'::geography, 'active'),
  ('Capitol Wellness Solutions - O''neal Lane', 'capitol-wellness-solutions-o-neal-lane', '1940 O''neal Lane', 'Baton Rouge', 'LA', '70816', '225-529-1420', null, null, 'LA-LDH-006', true, false, false, true, 'SRID=4326;POINT(-91.007646538779 30.440700806098)'::geography, 'active'),
  ('Capitol Wellness Solutions - Prairieville', 'capitol-wellness-solutions-prairieville', '17097 Airline Hwy', 'Prairieville', 'LA', '70769', '225-401-6240', null, null, 'LA-LDH-007', true, false, false, true, 'SRID=4326;POINT(-90.97742727466 30.316275870673)'::geography, 'active'),
  ('Green Leaf Dispensary', 'green-leaf-dispensary', '174 Arlington Street', 'Morgan City', 'LA', '70280', '985-263-3125', null, null, 'LA-LDH-008', true, false, false, true, 'SRID=4326;POINT(-91.262953305772 29.684350707469)'::geography, 'active'),
  ('Green Leaf Dispensary - Houma', 'green-leaf-dispensary-houma', '6048 W. Park Avenue', 'Houma', 'LA', '70364', '985-360-3372', null, null, 'LA-LDH-009', true, false, false, true, 'SRID=4326;POINT(-90.756197318305 29.630970082876)'::geography, 'active'),
  ('The Apothecary Shoppe', 'the-apothecary-shoppe', '620 Guilbeau Road, Suite A', 'Lafayette', 'LA', '70506', '337-345-4500', null, null, 'LA-LDH-010', true, false, false, true, 'SRID=4326;POINT(-92.072801086365 30.200224135598)'::geography, 'active'),
  ('The Apothecary Shoppe - New Iberia', 'the-apothecary-shoppe-new-iberia', '1700 Center Street', 'New Iberia', 'LA', '70560', '337-345-4500', null, null, 'LA-LDH-012', true, false, false, true, 'SRID=4326;POINT(-91.836568211647 29.988389684101)'::geography, 'active'),
  ('Medicis - Jennings', 'medicis-jennings', '1920 Evangeline Road', 'Jennings', 'LA', '70546', '337-218-4643', null, null, 'LA-LDH-014', true, false, false, true, 'SRID=4326;POINT(-92.635893474592 30.239725247931)'::geography, 'active'),
  ('Medicis - Sulphur', 'medicis-sulphur', '303 South Cities Service Hwy.', 'Sulphur', 'LA', '70663', '337-244-6638', null, null, 'LA-LDH-015', true, false, false, true, 'SRID=4326;POINT(-93.325385392552 30.220164234368)'::geography, 'active'),
  ('The Medicine Cabinet Pharmacy', 'the-medicine-cabinet-pharmacy', '403 Bolton Avenue', 'Alexandria', 'LA', '71301', '318-545-4460', null, null, 'LA-LDH-016', true, false, false, true, 'SRID=4326;POINT(-92.457029880012 31.30700544175)'::geography, 'active'),
  ('The Medicine Cabinet Pharmacy - Leesville', 'the-medicine-cabinet-pharmacy-leesville', '111 W. Harriet Street', 'Leesville', 'LA', '71446', '318-487-4460', null, null, 'LA-LDH-018', true, false, false, true, 'SRID=4326;POINT(-93.263863501101 31.140477149702)'::geography, 'active'),
  ('Hope Pharmacy', 'hope-pharmacy', '4590 E. Texas Street', 'Bossier City', 'LA', '71111', '318-402-1819', null, null, 'LA-LDH-019', true, false, false, true, 'SRID=4326;POINT(-93.672304765327 32.533373066007)'::geography, 'active'),
  ('Hope Pharmacy - Shreveport', 'hope-pharmacy-shreveport', '9352 Mansfield Road', 'Shreveport', 'LA', '71118', '318-533-4952', null, null, 'LA-LDH-021', true, false, false, true, 'SRID=4326;POINT(-93.808419704173 32.398041399264)'::geography, 'active'),
  ('Delta Medmar', 'delta-medmar', '1707 Mckeen Place', 'Monroe', 'LA', '71201', '318-855-3381', null, null, 'LA-LDH-022', true, false, false, true, 'SRID=4326;POINT(-92.116652273443 32.524820798114)'::geography, 'active'),
  ('Delta Medmar - Ruston', 'delta-medmar-ruston', '746 Celebrity Drive', 'Ruston', 'LA', '71270', '318-974-9492', null, null, 'LA-LDH-024', true, false, false, true, 'SRID=4326;POINT(-92.629697798537 32.543443014393)'::geography, 'active'),
  ('Willow Pharmacy', 'willow-pharmacy', '69090 Highway 190 Service Road', 'Covington', 'LA', '70433', '985-792-2391', null, null, 'LA-LDH-025', true, false, false, true, 'SRID=4326;POINT(-90.083488136395 30.430937776511)'::geography, 'active'),
  ('Willow Pharmacy - Slidell', 'willow-pharmacy-slidell', '796 East I-10 Service Road', 'Slidell', 'LA', '70461', '985-288-2660', null, null, 'LA-LDH-026', true, false, false, true, 'SRID=4326;POINT(-89.748725466197 30.284227418981)'::geography, 'active'),
  ('Willow Pharmacy - Hammond', 'willow-pharmacy-hammond', '1410 Sw Railroad Avenue', 'Hammond', 'LA', '70403', '985-520-0099', null, null, 'LA-LDH-027', true, false, false, true, 'SRID=4326;POINT(-90.456880732419 30.488926725708)'::geography, 'active')
on conflict (slug) do nothing;
