-- Seed: real licensed cannabis retailers.
-- Generated by scripts/import-la-dispensaries.mjs from C:\Users\jetni\AppData\Local\Temp/ri-licenses-geo.csv
-- Source: Rhode Island Cannabis Control Commission (official licensed-compassion-centers page, manually transcribed 2026-07-01; geocoded via US Census batch geocoder). Public record / attribution.
-- Filter: all cities, active retailers + microbusiness + non-storefront.
-- Records: 9
insert into public.dispensaries
  (name, slug, address, city, state, zip, phone, email, website, license_number,
   is_medical, is_recreational, is_delivery, is_pickup, location, status)
values
  ('Thomas C. Slater Compassion Center', 'thomas-c-slater-compassion-center', '1 Corliss Street', 'Providence', 'RI', '02904', '401-274-1000', null, null, 'RI-CCC-001', true, true, false, true, 'SRID=4326;POINT(-71.414404578734 41.838067732489)'::geography, 'active'),
  ('Newport Cannabis CO.', 'newport-cannabis-co', '1637 West Main Road', 'Portsmouth', 'RI', '02871', '401-293-5987', null, null, 'RI-CCC-002', true, true, false, true, 'SRID=4326;POINT(-71.251761909825 41.577031080976)'::geography, 'active'),
  ('Rise Warwick', 'rise-warwick', '444 Quaker Lane', 'Warwick', 'RI', '02886', '401-889-3990', null, null, 'RI-CCC-003', true, true, false, true, 'SRID=4326;POINT(-71.500367896434 41.682762635092)'::geography, 'active'),
  ('Sweetspot Dispensary', 'sweetspot-dispensary-exeter', '560 South County Trail, Building B', 'Exeter', 'RI', '02822', '401-271-3869', null, null, 'RI-CCC-004', true, true, false, true, 'SRID=4326;POINT(-71.550445470988 41.527852798364)'::geography, 'active'),
  ('Aura Of Rhode Island', 'aura-of-rhode-island', '1136 Lonsdale Avenue', 'Central Falls', 'RI', '02806', '401-335-5356', null, null, 'RI-CCC-005', true, true, false, true, 'SRID=4326;POINT(-71.404136876681 41.894049990986)'::geography, 'active'),
  ('Mother Earth Wellness', 'mother-earth-wellness', '125 Esten Avenue', 'Pawtucket', 'RI', '02860', '401-352-4300', null, null, 'RI-CCC-006', true, true, false, true, 'SRID=4326;POINT(-71.402383707015 41.864744890341)'::geography, 'active'),
  ('Solar Cannabis CO.', 'solar-cannabis-co', '65 Meadow Street, Unit A', 'Warwick', 'RI', '02886', '401-642-1919', null, null, 'RI-CCC-007', true, true, false, true, 'SRID=4326;POINT(-71.461490208572 41.696547042073)'::geography, 'active'),
  ('Green Wave Cc', 'green-wave-cc', '187 Danielson Pike', 'Foster', 'RI', '02825', '774-203-8551', null, null, 'RI-CCC-008', true, true, false, true, 'SRID=4326;POINT(-71.791973983156 41.795060194795)'::geography, 'active'),
  ('New Leaf Compassion Center', 'new-leaf-compassion-center', '2000 Diamond Hill Road', 'Woonsocket', 'RI', '02895', null, null, null, 'RI-CCC-009', true, true, false, true, 'SRID=4326;POINT(-71.470863380283 42.015101987811)'::geography, 'active')
on conflict (slug) do nothing;
