-- Seed: real licensed cannabis retailers.
-- Generated by scripts/import-la-dispensaries.mjs from C:\Users\jetni\AppData\Local\Temp/hi-licenses-geo.csv
-- Source: Hawaii Dept. of Health (official per-island dispensary-location pages, manually transcribed 2026-07-01; geocoded via US Census batch geocoder). Public record / attribution.
-- Filter: all cities, active retailers + microbusiness + non-storefront.
-- Records: 24
insert into public.dispensaries
  (name, slug, address, city, state, zip, phone, email, website, license_number,
   is_medical, is_recreational, is_delivery, is_pickup, location, status)
values
  ('Aloha Green - Honolulu', 'aloha-green-honolulu', '3131 North Nimitz Hwy.', 'Honolulu', 'HI', '96819', null, null, null, 'HI-DOH-001', true, false, false, true, 'SRID=4326;POINT(-157.908141043028 21.335909931046)'::geography, 'active'),
  ('Aloha Green - Kapolei', 'aloha-green-kapolei', '92-1047 Olani St., #1-110', 'Kapolei', 'HI', '96707', null, null, null, 'HI-DOH-002', true, false, false, true, 'SRID=4326;POINT(-158.124703887408 21.340541119127)'::geography, 'active'),
  ('Aloha Green - King Street', 'aloha-green-king-street', '1314 S. King St.', 'Honolulu', 'HI', '96814', null, null, null, 'HI-DOH-003', true, false, false, true, 'SRID=4326;POINT(-157.84155334329 21.299004564577)'::geography, 'active'),
  ('Aloha Green - Waikiki', 'aloha-green-waikiki', '2113 Kalakaua Ave.', 'Honolulu', 'HI', '96815', null, null, null, 'HI-DOH-004', true, false, false, true, 'SRID=4326;POINT(-157.83070027536 21.281575735191)'::geography, 'active'),
  ('Cure Oahu - Kailua', 'cure-oahu-kailua', '70 Kihapai Street', 'Kailua', 'HI', '96734', null, null, null, 'HI-DOH-005', true, false, false, true, 'SRID=4326;POINT(-157.746417350345 21.394668652943)'::geography, 'active'),
  ('Cure Oahu - Kapolei', 'cure-oahu-kapolei', '4850 Kapolei Parkway Bldg. D #501', 'Kapolei', 'HI', '96707', null, null, null, 'HI-DOH-006', true, false, false, true, 'SRID=4326;POINT(-158.076347234119 21.328802381585)'::geography, 'active'),
  ('Cure Oahu - Honolulu', 'cure-oahu-honolulu', '727 Kapahulu Ave.', 'Honolulu', 'HI', '96816', null, null, null, 'HI-DOH-007', true, false, false, true, 'SRID=4326;POINT(-157.814047806649 21.280624778436)'::geography, 'active'),
  ('Noa Botanicals - Aiea', 'noa-botanicals-aiea', '98-302 Kamehameha Hwy', 'Aiea', 'HI', '96701', null, null, null, 'HI-DOH-008', true, false, false, true, 'SRID=4326;POINT(-157.93836788458 21.380030028741)'::geography, 'active'),
  ('Noa Botanicals - Honolulu', 'noa-botanicals-honolulu', '1308 Young Street', 'Honolulu', 'HI', '96814', null, null, null, 'HI-DOH-009', true, false, false, true, 'SRID=4326;POINT(-157.841093970365 21.29983380043)'::geography, 'active'),
  ('Noa Botanicals - Kaneohe', 'noa-botanicals-kaneohe', '46-028 Kawa St.', 'Kaneohe', 'HI', '96744', null, null, null, 'HI-DOH-010', true, false, false, true, 'SRID=4326;POINT(-157.803266941214 21.418206768178)'::geography, 'active'),
  ('Noa Botanicals - Waikiki', 'noa-botanicals-waikiki', '345 Royal Hawaiian Avenue', 'Honolulu', 'HI', '96815', null, null, null, 'HI-DOH-011', true, false, false, true, 'SRID=4326;POINT(-157.828212783561 21.280271473811)'::geography, 'active'),
  ('Hawaiian Ethos - Hilo', 'hawaiian-ethos-hilo', '578 Kanoelehua Ave.', 'Hilo', 'HI', '96720', null, null, null, 'HI-DOH-012', true, false, false, true, 'SRID=4326;POINT(-155.064371851623 19.713634828063)'::geography, 'active'),
  ('Hawaiian Ethos - Kona', 'hawaiian-ethos-kona', '73-5613 Olowalu St., Suite 7', 'Kailua-Kona', 'HI', '96740', null, null, null, 'HI-DOH-013', true, false, false, true, 'SRID=4326;POINT(-156.018855781555 19.691186671936)'::geography, 'active'),
  ('Hawaiian Ethos - Waimea', 'hawaiian-ethos-waimea', '64-1035 Mamalahoa Hwy., Unit J', 'Kamuela', 'HI', '96743', null, null, null, 'HI-DOH-014', true, false, false, true, 'SRID=4326;POINT(-155.659031730199 20.025344380228)'::geography, 'active'),
  ('Big Island Grown - Hilo', 'big-island-grown-hilo', '750 Kanoelehua Ave., Suite 104', 'Hilo', 'HI', '96720', null, null, null, 'HI-DOH-015', true, false, false, true, 'SRID=4326;POINT(-155.064380849205 19.708236829742)'::geography, 'active'),
  ('Big Island Grown - Kona', 'big-island-grown-kona', '74-5617 Pawai Place', 'Kailua-Kona', 'HI', '96740', null, null, null, 'HI-DOH-016', true, false, false, true, 'SRID=4326;POINT(-155.998682905052 19.643864805162)'::geography, 'active'),
  ('Big Island Grown - Waimea', 'big-island-grown-waimea', '64-1040 Mamalahoa Hwy.', 'Waimea', 'HI', '96743', null, null, null, 'HI-DOH-017', true, false, false, true, 'SRID=4326;POINT(-155.659620575119 20.025263895547)'::geography, 'active'),
  ('Maui Grown Therapies - Kahului', 'maui-grown-therapies-kahului', '44 Paa St.', 'Kahului', 'HI', '96732', null, null, null, 'HI-DOH-018', true, false, false, true, 'SRID=4326;POINT(-156.496856893778 20.867536712763)'::geography, 'active'),
  ('Maui Grown Therapies - Kihei', 'maui-grown-therapies-kihei', '1215 S. Kihei Rd, Unit D2', 'Kihei', 'HI', '96753', null, null, null, 'HI-DOH-019', true, false, false, true, 'SRID=4326;POINT(-156.45602899792 20.751115157477)'::geography, 'active'),
  ('Maui Grown Therapies - Pukalani', 'maui-grown-therapies-pukalani', '7 Aewa Place, Unit 3', 'Makawao', 'HI', '96768', null, null, null, 'HI-DOH-020', true, false, false, true, 'SRID=4326;POINT(-156.336205627176 20.835678912271)'::geography, 'active'),
  ('Pono Life Sciences Maui - Kihei', 'pono-life-sciences-maui-kihei', '95 E. Lipoa St', 'Kihei', 'HI', '96753', null, null, null, 'HI-DOH-021', true, false, false, true, 'SRID=4326;POINT(-156.452140483861 20.747983382963)'::geography, 'active'),
  ('Pono Life Sciences Maui - Lahaina', 'pono-life-sciences-maui-lahaina', '60 Ulupono Street #8', 'Lahaina', 'HI', '96761', null, null, null, 'HI-DOH-022', true, false, false, true, 'SRID=4326;POINT(-156.677667164856 20.885065092925)'::geography, 'active'),
  ('Green Aloha - Kapaa', 'green-aloha-kapaa', '4-1565 Kuhio Hwy #3', 'Kapaa', 'HI', '96746', null, null, null, 'HI-DOH-023', true, false, false, true, 'SRID=4326;POINT(-159.314373448355 22.079833739556)'::geography, 'active'),
  ('Green Aloha - Koloa', 'green-aloha-koloa', '2827 Poipu Rd.', 'Koloa', 'HI', '96756', null, null, null, 'HI-DOH-024', true, false, false, true, 'SRID=4326;POINT(-159.46802263874 21.885246255033)'::geography, 'active')
on conflict (slug) do nothing;
