-- Seed: real licensed cannabis retailers.
-- Generated by scripts/import-la-dispensaries.mjs from C:\Users\jetni\AppData\Local\Temp/ia-licenses-geo.csv
-- Source: Iowa HHS (official dispensary-locations page + operator sites, manually transcribed 2026-07-01; geocoded via US Census batch geocoder). Public record / attribution.
-- Filter: all cities, active retailers + microbusiness + non-storefront.
-- Records: 4
insert into public.dispensaries
  (name, slug, address, city, state, zip, phone, email, website, license_number,
   is_medical, is_recreational, is_delivery, is_pickup, location, status)
values
  ('Bud & Mary''s - Sioux City', 'bud-and-mary-s-sioux-city', '5700 Sunnybrook Drive', 'Sioux City', 'IA', '51106', null, null, null, 'IA-HHS-001', true, false, false, true, 'SRID=4326;POINT(-96.331347265194 42.447807466965)'::geography, 'active'),
  ('Iowa Cannabis Company - Waterloo', 'iowa-cannabis-company-waterloo', '1955 Laporte Rd', 'Waterloo', 'IA', '50702', null, null, null, 'IA-HHS-003', true, false, false, true, 'SRID=4326;POINT(-92.319975606285 42.466621718785)'::geography, 'active'),
  ('Iowa Cannabis Company - Iowa City', 'iowa-cannabis-company-iowa-city', '322 Hwy 1 W', 'Iowa City', 'IA', '52246', null, null, null, 'IA-HHS-004', true, false, false, true, 'SRID=4326;POINT(-91.543602336322 41.647594071294)'::geography, 'active'),
  ('Iowa Cannabis Company - Council Bluffs', 'iowa-cannabis-company-council-bluffs', '3615 9th Ave', 'Council Bluffs', 'IA', '51501', null, null, null, 'IA-HHS-005', true, false, false, true, 'SRID=4326;POINT(-95.904956721851 41.25364045143)'::geography, 'active')
on conflict (slug) do nothing;
