-- Seed: real licensed cannabis retailers.
-- Generated by scripts/import-la-dispensaries.mjs from C:\Users\jetni\AppData\Local\Temp/tx-licenses-geo2.csv
-- Source: Texas Compassionate Use Program (Texas Original via public StoreRocket API; Fluent + goodblend manually transcribed 2026-07-01; geocoded via US Census batch geocoder). Public record / attribution.
-- Filter: all cities, active retailers + microbusiness + non-storefront.
-- Records: 28
insert into public.dispensaries
  (name, slug, address, city, state, zip, phone, email, website, license_number,
   is_medical, is_recreational, is_delivery, is_pickup, location, status)
values
  ('Fluent - Houston', 'fluent-houston', '2620 W Sam Houston Pkwy S', 'Houston', 'TX', '77042', '713-489-3701', null, null, 'TX-DPS-001', true, false, false, true, 'SRID=4326;POINT(-95.5397 29.7307)'::geography, 'active'),
  ('Fluent - Schulenburg', 'fluent-schulenburg', '8381 West Us 90', 'Schulenburg', 'TX', '78956', '713-489-3701', null, null, 'TX-DPS-002', true, false, false, true, 'SRID=4326;POINT(-96.9316 29.6866)'::geography, 'active'),
  ('Goodblend - South Austin', 'goodblend-south-austin', '7105 E. Riverside Drive', 'Austin', 'TX', null, null, null, null, 'TX-DPS-003', true, false, false, true, 'SRID=4326;POINT(-97.696238720684 30.221627845562)'::geography, 'active'),
  ('Goodblend - San Antonio', 'goodblend-san-antonio', '18720 Stone Oak Pkwy, #107', 'San Antonio', 'TX', null, null, null, null, 'TX-DPS-004', true, false, false, true, 'SRID=4326;POINT(-98.49275592826 29.610074644279)'::geography, 'active'),
  ('Goodblend - Nacogdoches', 'goodblend-nacogdoches', '1320 N University Dr', 'Nacogdoches', 'TX', null, null, null, null, 'TX-DPS-006', true, false, false, true, 'SRID=4326;POINT(-94.639074639146 31.614685958076)'::geography, 'active'),
  ('Goodblend - Houston', 'goodblend-houston', '9432 Katy Fwy, #400', 'Houston', 'TX', null, null, null, null, 'TX-DPS-007', true, false, false, true, 'SRID=4326;POINT(-95.525474370114 29.785045779038)'::geography, 'active'),
  ('Goodblend - Austin', 'goodblend-austin', '2217 Park Bend Dr #300', 'Austin', 'TX', null, null, null, null, 'TX-DPS-008', true, false, false, true, 'SRID=4326;POINT(-97.703908605771 30.408503649744)'::geography, 'active'),
  ('Goodblend - Wichita Falls', 'goodblend-wichita-falls', '1722 9th St', 'Wichita Falls', 'TX', null, null, null, null, 'TX-DPS-009', true, false, false, true, 'SRID=4326;POINT(-98.504206777634 33.903836133203)'::geography, 'active'),
  ('Goodblend - Fort Worth', 'goodblend-fort-worth', '1307 8th Ave Suite #603', 'Fort Worth', 'TX', null, null, null, null, 'TX-DPS-010', true, false, false, true, 'SRID=4326;POINT(-97.343656602777 32.730560907738)'::geography, 'active'),
  ('Goodblend - Colleyville', 'goodblend-colleyville', '6213 Colleyville Blvd, Suite 100', 'Colleyville', 'TX', null, null, null, null, 'TX-DPS-011', true, false, false, true, 'SRID=4326;POINT(-97.143556892311 32.898706230889)'::geography, 'active'),
  ('Goodblend - Missouri City', 'goodblend-missouri-city', '4220 Cartwright Rd, Suite 303', 'Missouri City', 'TX', null, null, null, null, 'TX-DPS-012', true, false, false, true, 'SRID=4326;POINT(-95.579104731975 29.583280490756)'::geography, 'active'),
  ('Texas Original - Fort Worth', 'texas-original-fort-worth', '2812 Horne Street, Suite 200', 'Fort Worth', 'TX', '76107', '512-614-0343', null, null, 'TX-DPS-013', true, false, false, true, 'SRID=4326;POINT(-97.4082476 32.7324298)'::geography, 'active'),
  ('Texas Original - Houston Heights', 'texas-original-houston-heights', '1714 Houston Ave', 'Houston', 'TX', '77007', '(512) 614-0343', null, null, 'TX-DPS-014', true, false, false, true, 'SRID=4326;POINT(-95.3721118 29.773516)'::geography, 'active'),
  ('Texas Original - Hurst', 'texas-original-hurst', '760 Airport Freeway, Ste 300', 'Hurst', 'TX', '76054', '(512) 614-0343', null, null, 'TX-DPS-015', true, false, false, true, 'SRID=4326;POINT(-97.1841702 32.8407043)'::geography, 'active'),
  ('Texas Original - Lubbock', 'texas-original-lubbock', '421 Frankford Ave', 'Lubbock', 'TX', '79416', '(512) 614-0343', null, null, 'TX-DPS-016', true, false, false, true, 'SRID=4326;POINT(-101.9392987 33.5911109)'::geography, 'active'),
  ('Texas Original - Nacogdoches', 'texas-original-nacogdoches', '1320 N University Dr', 'Nacogdoches', 'TX', '75961', '(512) 614-0343', null, null, 'TX-DPS-017', true, false, false, true, 'SRID=4326;POINT(-94.6381799 31.6150209)'::geography, 'active'),
  ('Texas Original - North Austin', 'texas-original-north-austin', '10222 Pecan Park Blvd, Ste 3', 'Austin', 'TX', '78729', '(512) 614-0343', null, null, 'TX-DPS-018', true, false, false, true, 'SRID=4326;POINT(-97.7894291 30.4644165)'::geography, 'active'),
  ('Texas Original - Plano', 'texas-original-plano', '601 West 15th St, Ste 102', 'Plano', 'TX', '75075', '(512) 614-0343', null, null, 'TX-DPS-019', true, false, false, true, 'SRID=4326;POINT(-96.7125513 33.0195036)'::geography, 'active'),
  ('Texas Original - San Antonio', 'texas-original-san-antonio', '1464 Austin Hwy, Ste 104', 'San Antonio', 'TX', '78209', '(512) 614-0343', null, null, 'TX-DPS-020', true, false, false, true, 'SRID=4326;POINT(-98.4340135 29.4930971)'::geography, 'active'),
  ('Texas Original - South Austin', 'texas-original-south-austin', '12701 Lowden Ln, Bldg 501', 'Manchaca', 'TX', '78652', '(512) 614-0343', null, null, 'TX-DPS-021', true, false, false, true, 'SRID=4326;POINT(-97.8333563 30.1338932)'::geography, 'active'),
  ('Texas Original - The Woodlands', 'texas-original-the-woodlands', '1500 Research Forest Dr, Ste 120', 'The Woodlands', 'TX', '77381', '(512) 614-0343', null, null, 'TX-DPS-022', true, false, false, true, 'SRID=4326;POINT(-95.459557 30.178401)'::geography, 'active'),
  ('Texas Original - Tyler', 'texas-original-tyler', '11980 State Hwy 64, Suite C', 'Tyler', 'TX', '75707', '(512) 614-0343', null, null, 'TX-DPS-023', true, false, false, true, 'SRID=4326;POINT(-95.2098678 32.3177006)'::geography, 'active'),
  ('Texas Original - Conroe', 'texas-original-conroe', '610 N Loop 336 E', 'Conroe', 'TX', '77301', '512-614-0343', null, null, 'TX-DPS-024', true, false, false, true, 'SRID=4326;POINT(-95.4432604 30.3395537)'::geography, 'active'),
  ('Texas Original - Frisco', 'texas-original-frisco', '8380 Warren Parkway, Bldg 1, Ste 100', 'Frisco', 'TX', '75034', '(512) 614-0343', null, null, 'TX-DPS-025', true, false, false, true, 'SRID=4326;POINT(-96.8143639 33.1084588)'::geography, 'active'),
  ('Texas Original - New Braunfels', 'texas-original-new-braunfels', '1433 Hanz Dr, Suite 110', 'New Braunfels', 'TX', '78130', '512-614-0343', null, null, 'TX-DPS-026', true, false, false, true, 'SRID=4326;POINT(-98.1019554 29.7284795)'::geography, 'active'),
  ('Texas Original - North Dallas', 'texas-original-north-dallas', '10400 N Central Expressway', 'Dallas', 'TX', '75321', '(512) 614-0343', null, null, 'TX-DPS-027', true, false, false, true, 'SRID=4326;POINT(-96.7683122 32.8880213)'::geography, 'active'),
  ('Texas Original - Sugar Land', 'texas-original-sugar-land', '118 Eldridge Rd, Suite A', 'Sugar Land', 'TX', '77478', '(512) 614-0343', null, null, 'TX-DPS-028', true, false, false, true, 'SRID=4326;POINT(-95.6181538 29.6247405)'::geography, 'active'),
  ('Texas Original - Waco', 'texas-original-waco', '6431 Sanger Ave', 'Waco', 'TX', '76710', '(512) 614-0343', null, null, 'TX-DPS-029', true, false, false, true, 'SRID=4326;POINT(-97.1961745 31.521379)'::geography, 'active')
on conflict (slug) do nothing;
