-- Seed: real licensed cannabis retailers.
-- Generated by scripts/import-la-dispensaries.mjs from C:\Users\jetni\AppData\Local\Temp/ga-licenses.csv
-- Source: Georgia Access to Medical Cannabis Commission (official public map, gmcc.ga.gov/patients/dispensaries, fetched 2026-07-01). Public record / attribution.
-- Filter: all cities, active retailers + microbusiness + non-storefront.
-- Records: 17
insert into public.dispensaries
  (name, slug, address, city, state, zip, phone, email, website, license_number,
   is_medical, is_recreational, is_delivery, is_pickup, location, status)
values
  ('Trulieve Macon', 'trulieve-macon', '3556 Riverside Drive, Suite A', 'Macon', 'GA', '31210', null, null, null, 'DISP0001', true, false, false, true, 'SRID=4326;POINT(-83.6833325 32.8975623)'::geography, 'active'),
  ('Trulieve Marietta', 'trulieve-marietta', '220 Cobb Parkway North, Suite 600', 'Marietta', 'GA', '30062', null, null, null, 'DISP0002', true, false, false, true, 'SRID=4326;POINT(-84.5225041 33.9556006)'::geography, 'active'),
  ('Trulieve Pooler', 'trulieve-pooler', '2003 Pooler Parkway', 'Pooler', 'GA', '31322', null, null, null, 'DISP0003', true, false, false, true, 'SRID=4326;POINT(-81.2799086 32.0811698)'::geography, 'active'),
  ('Botanical Sciences Marietta', 'botanical-sciences-marietta', '2468 Windy Hill Rd, Suite 900', 'Marietta', 'GA', '30067', null, null, null, 'DISP0004', true, false, false, true, 'SRID=4326;POINT(-84.4816349 33.902355)'::geography, 'active'),
  ('Botanical Sciences Pooler', 'botanical-sciences-pooler', '100 Zoya Lane, Suite 112', 'Pooler', 'GA', '31322', null, null, null, 'DISP0005', true, false, false, true, 'SRID=4326;POINT(-81.2769441 32.0870758)'::geography, 'active'),
  ('Trulieve Newnan', 'trulieve-newnan', '1690 Highway 34 East, Suite D', 'Newnan', 'GA', '30265', null, null, null, 'DISP0006', true, false, false, true, 'SRID=4326;POINT(-84.7251988 33.4018397)'::geography, 'active'),
  ('Botanical Sciences Chamblee', 'botanical-sciences-chamblee', '3927 Buford Hwy Ne', 'Atlanta', 'GA', '30345', null, null, null, 'DISP0007', true, false, false, true, 'SRID=4326;POINT(-84.3114939 33.8579104)'::geography, 'active'),
  ('Botanical Sciences Stockbridge', 'botanical-sciences-stockbridge', '1791 Rock Quarry Rd', 'Stockbridge', 'GA', '30281', null, null, null, 'DISP0008', true, false, false, true, 'SRID=4326;POINT(-84.2289087 33.5079524)'::geography, 'active'),
  ('Trulieve Evans', 'trulieve-evans', '4218 Washington Rd, Unit 1', 'Evans', 'GA', '30809', null, null, null, 'DISP0009', true, false, false, true, 'SRID=4326;POINT(-82.121703 33.523809)'::geography, 'active'),
  ('Fine Fettle Smyrna', 'fine-fettle-smyrna', '2110 Paces Ferry Road Se', 'Smyrna', 'GA', '30080', null, null, null, 'DISP0011', true, false, false, true, 'SRID=4326;POINT(-84.4916136 33.8643372)'::geography, 'active'),
  ('Fine Fettle Decatur', 'fine-fettle-decatur', '2607 Lawrenceville Highway', 'Decatur', 'GA', '30033', null, null, null, 'DISP0013', true, false, false, true, 'SRID=4326;POINT(-84.2620781 33.8228465)'::geography, 'active'),
  ('Fine Fettle Athens', 'fine-fettle-athens', '3035 Atlanta Highway', 'Athens', 'GA', '30606', null, null, null, 'DISP0012', true, false, false, true, 'SRID=4326;POINT(-83.439548 33.9431955)'::geography, 'active'),
  ('Trulieve Columbus', 'trulieve-columbus', '4328 Armour Road', 'Columbus', 'GA', '31904', null, null, null, 'DISP0014', true, false, false, true, 'SRID=4326;POINT(-84.9522879 32.5042004)'::geography, 'active'),
  ('Treevana Milledgeville', 'treevana-milledgeville', '3015 Heritage Place, Suite B', 'Milledgeville', 'GA', '31061', null, null, null, 'DISP0015', true, false, false, true, 'SRID=4326;POINT(-83.259218 33.1182227)'::geography, 'active'),
  ('Botanical Sciences Atlanta', 'botanical-sciences-atlanta', '1532 Howell Mill Rd.', 'Atlanta', 'GA', '30318', null, null, null, 'DISP0018', true, false, false, true, 'SRID=4326;POINT(-84.4164236 33.7974041)'::geography, 'active'),
  ('True Bliss Atlanta', 'true-bliss-atlanta', '66 Peachtree Street Nw', 'Atlanta', 'GA', '30303', null, null, null, 'DISP0017', true, false, false, true, 'SRID=4326;POINT(-84.3890696 33.7556122)'::geography, 'active'),
  ('Fine Fettle Evans', 'fine-fettle-evans', '4300 Towne Centre', 'Evans', 'GA', '30809', null, null, null, 'DISP0020', true, false, false, true, 'SRID=4326;POINT(-82.1261091 33.5322068)'::geography, 'active')
on conflict (slug) do nothing;
