-- Seed: real licensed cannabis retailers.
-- Generated by scripts/import-la-dispensaries.mjs from C:\Users\jetni\AppData\Local\Temp/ut-licenses-geo.csv
-- Source: Utah Dept. of Health and Human Services (official pharmacy-locations page, manually transcribed 2026-07-01; geocoded via US Census batch geocoder). Public record / attribution.
-- Filter: all cities, active retailers + microbusiness + non-storefront.
-- Records: 14
insert into public.dispensaries
  (name, slug, address, city, state, zip, phone, email, website, license_number,
   is_medical, is_recreational, is_delivery, is_pickup, location, status)
values
  ('Beehive Farmacy - Brigham City', 'beehive-farmacy-brigham-city', '870 W 1150 S, Suite C', 'Brigham City', 'UT', '84302', '435-919-0966', null, null, 'UT-DHHS-001', true, false, false, true, 'SRID=4326;POINT(-112.031322330152 41.485740189878)'::geography, 'active'),
  ('Beehive Farmacy - Salt Lake City', 'beehive-farmacy-salt-lake-city', '1991 S 3600 W', 'Salt Lake City', 'UT', '84104', '385-212-0088', null, null, 'UT-DHHS-002', true, false, false, true, 'SRID=4326;POINT(-111.97710008514 40.727182886823)'::geography, 'active'),
  ('Bloc Pharmacy - South Jordan', 'bloc-pharmacy-south-jordan', '10392 South Jordan Gateway', 'South Jordan', 'UT', '84095', '385-249-9400', null, null, 'UT-DHHS-003', true, false, false, true, 'SRID=4326;POINT(-111.902575926995 40.562128162737)'::geography, 'active'),
  ('Bloc Pharmacy - St. George', 'bloc-pharmacy-st-george', '1624 S Convention Center Drive', 'St. George', 'UT', '84790', '435-216-3400', null, null, 'UT-DHHS-004', true, false, false, true, 'SRID=4326;POINT(-113.582507938886 37.08043843566)'::geography, 'active'),
  ('Curaleaf - Lehi', 'curaleaf-lehi', '3633 N Thanksgiving Way', 'Lehi', 'UT', '84043', '385-338-8010', null, null, 'UT-DHHS-005', true, false, false, true, 'SRID=4326;POINT(-111.894645320506 40.433215913441)'::geography, 'active'),
  ('Curaleaf - Park City', 'curaleaf-park-city', '1351 Kearns Blvd, Ste 110-B', 'Park City', 'UT', '84060', '435-252-1052', null, null, 'UT-DHHS-006', true, false, false, true, 'SRID=4326;POINT(-111.502919632663 40.661787734041)'::geography, 'active'),
  ('Curaleaf - Provo', 'curaleaf-provo', '222 N Draper Lane', 'Provo', 'UT', '84601', '801-872-7447', null, null, 'UT-DHHS-008', true, false, false, true, 'SRID=4326;POINT(-111.686354486927 40.236461626615)'::geography, 'active'),
  ('Dragonfly Wellness - Salt Lake City', 'dragonfly-wellness-salt-lake-city', '711 South State Street', 'Salt Lake City', 'UT', '84111', '801-413-6945', null, null, 'UT-DHHS-009', true, false, false, true, 'SRID=4326;POINT(-111.888142130249 40.753465429873)'::geography, 'active'),
  ('Dragonfly Wellness - Price', 'dragonfly-wellness-price', '20 E Main Street', 'Price', 'UT', '84501', '435-637-3770', null, null, 'UT-DHHS-010', true, false, false, true, 'SRID=4326;POINT(-110.810827744166 39.599531441631)'::geography, 'active'),
  ('The Flower Shop - Logan', 'the-flower-shop-logan', '2150 N Main, Suite 1', 'North Logan', 'UT', '84341', '385-289-1800', null, null, 'UT-DHHS-011', true, false, false, true, 'SRID=4326;POINT(-111.834014472972 41.771491318986)'::geography, 'active'),
  ('The Flower Shop - Ogden', 'the-flower-shop-ogden', '3775 S Wall Ave', 'South Ogden', 'UT', '84405', '385-289-1800', null, null, 'UT-DHHS-012', true, false, false, true, 'SRID=4326;POINT(-111.979558135766 41.195094669411)'::geography, 'active'),
  ('The Forest', 'the-forest', '6041 State St', 'Murray', 'UT', '84107', '385-474-9505', null, null, 'UT-DHHS-013', true, false, false, true, 'SRID=4326;POINT(-111.888991210365 40.639575131353)'::geography, 'active'),
  ('Wholesomeco Cannabis', 'wholesomeco-cannabis', '580 W 100 N Suite 1', 'West Bountiful', 'UT', '84010', '801-695-4480', null, null, 'UT-DHHS-014', true, false, false, true, 'SRID=4326;POINT(-111.882494451211 40.895259211484)'::geography, 'active'),
  ('Zion Medicinal', 'zion-medicinal', '301 S Main Street', 'Cedar City', 'UT', '84720', '435-708-1630', null, null, 'UT-DHHS-015', true, false, false, true, 'SRID=4326;POINT(-113.061504097525 37.67209333328)'::geography, 'active')
on conflict (slug) do nothing;
