-- Seed: curated real multi-state US cannabis consumer brands.
-- National/MSO + notable per-state brands, additive to the CA brand set.
-- Hand-curated (no public brand registry exists; not scraped). Unowned.
-- Brands: 79
insert into public.brands (name, slug, description)
values
  ('Cresco', 'cresco', 'National cannabis flower brand.'),
  ('Rythm', 'rythm', 'National cannabis flower brand.'),
  ('Good Green', 'good-green', 'National cannabis flower brand.'),
  ('&Shine', 'and-shine', 'National cannabis flower brand.'),
  ('High Supply', 'high-supply', 'National cannabis flower brand.'),
  ('FloraCal', 'floracal', 'National cannabis flower brand.'),
  ('Good News', 'good-news', 'National cannabis edibles brand.'),
  ('Mindy''s', 'mindy-s', 'National cannabis edibles brand.'),
  ('Beboe', 'beboe', 'National cannabis vape & concentrate brand.'),
  ('incredibles', 'incredibles', 'National cannabis edibles brand.'),
  ('1906', '1906', 'National cannabis edibles brand.'),
  ('Grön', 'gron', 'National cannabis edibles brand.'),
  ('Cheeba Chews', 'cheeba-chews', 'National cannabis edibles brand.'),
  ('Bhang', 'bhang', 'National cannabis edibles brand.'),
  ('Mr. Moxey''s', 'mr-moxey-s', 'National cannabis edibles brand.'),
  ('District Edibles', 'district-edibles', 'National cannabis edibles brand.'),
  ('Dixie Elixirs', 'dixie-elixirs', 'National cannabis beverage brand.'),
  ('Dosist', 'dosist', 'National cannabis vape & concentrate brand.'),
  ('Airo', 'airo', 'National cannabis vape & concentrate brand.'),
  ('O.pen', 'o-pen', 'National cannabis vape & concentrate brand.'),
  ('Timeless', 'timeless', 'National cannabis vape & concentrate brand.'),
  ('Buddies', 'buddies', 'National cannabis concentrate & extract brand.'),
  ('Willie''s Reserve', 'willie-s-reserve', 'National cannabis flower brand.'),
  ('Binske', 'binske', 'National cannabis brand.'),
  ('Curaleaf', 'curaleaf', 'National cannabis brand.'),
  ('Grassroots', 'grassroots', 'National cannabis flower brand.'),
  ('B-Noble', 'b-noble', 'National cannabis vape & concentrate brand.'),
  ('Trulieve', 'trulieve', 'National cannabis brand.'),
  ('Roll One', 'roll-one', 'National cannabis flower brand.'),
  ('Modern Flower', 'modern-flower', 'National cannabis flower brand.'),
  ('Verano', 'verano', 'National cannabis brand.'),
  ('Encore', 'encore', 'National cannabis edibles brand.'),
  ('Savvy', 'savvy', 'National cannabis flower brand.'),
  ('Avexia', 'avexia', 'National cannabis wellness & tincture brand.'),
  ('MÜV', 'muv', 'National cannabis brand.'),
  ('Ayr', 'ayr', 'National cannabis brand.'),
  ('Kynd', 'kynd', 'National cannabis flower brand.'),
  ('Levia', 'levia', 'National cannabis beverage brand.'),
  ('Columbia Care', 'columbia-care', 'National cannabis brand.'),
  ('Seed & Strain', 'seed-and-strain', 'National cannabis flower brand.'),
  ('Classix', 'classix', 'National cannabis flower brand.'),
  ('hedy', 'hedy', 'National cannabis edibles brand.'),
  ('Good Day Farm', 'good-day-farm', 'National cannabis flower brand.'),
  ('Minntz', 'minntz', 'National cannabis flower brand.'),
  ('Khalifa Kush', 'khalifa-kush', 'National cannabis flower brand.'),
  ('Runtz', 'runtz', 'National cannabis flower brand.'),
  ('Monogram', 'monogram', 'National cannabis flower brand.'),
  ('Houseplant', 'houseplant', 'National cannabis flower brand.'),
  ('Tyson 2.0', 'tyson-2-0', 'National cannabis flower brand.'),
  ('Stratos', 'stratos', 'Colorado cannabis edibles brand.'),
  ('Coda Signature', 'coda-signature', 'Colorado cannabis edibles brand.'),
  ('Dialed In Gummies', 'dialed-in-gummies', 'Colorado cannabis edibles brand.'),
  ('Robhots', 'robhots', 'Colorado cannabis edibles brand.'),
  ('Americanna', 'americanna', 'Colorado cannabis edibles brand.'),
  ('Highly Edible', 'highly-edible', 'Colorado cannabis edibles brand.'),
  ('Veritas Fine Cannabis', 'veritas-fine-cannabis', 'Colorado cannabis flower brand.'),
  ('Green Dot Labs', 'green-dot-labs', 'Colorado cannabis concentrate & extract brand.'),
  ('Phat Panda', 'phat-panda', 'Washington cannabis flower brand.'),
  ('Fairwinds', 'fairwinds', 'Washington cannabis wellness & tincture brand.'),
  ('Avitas', 'avitas', 'Washington cannabis vape & concentrate brand.'),
  ('Mfused', 'mfused', 'Washington cannabis vape & concentrate brand.'),
  ('Quill', 'quill', 'Oregon cannabis vape & concentrate brand.'),
  ('Pleasantrees', 'pleasantrees', 'Michigan cannabis flower brand.'),
  ('Skymint', 'skymint', 'Michigan cannabis flower brand.'),
  ('Common Citizen', 'common-citizen', 'Michigan cannabis flower brand.'),
  ('Insa', 'insa', 'Massachusetts cannabis brand.'),
  ('Nova Farms', 'nova-farms', 'Massachusetts cannabis flower brand.'),
  ('Fernway', 'fernway', 'Massachusetts cannabis vape & concentrate brand.'),
  ('Garden Remedies', 'garden-remedies', 'Massachusetts cannabis brand.'),
  ('Sunburn', 'sunburn', 'Florida cannabis flower brand.'),
  ('Fluent', 'fluent', 'Florida cannabis brand.'),
  ('Cannavative', 'cannavative', 'Nevada cannabis concentrate & extract brand.'),
  ('City Trees', 'city-trees', 'Nevada cannabis vape & concentrate brand.'),
  ('Aeriz', 'aeriz', 'Arizona cannabis flower brand.'),
  ('Item 9 Labs', 'item-9-labs', 'Arizona cannabis brand.'),
  ('Sublime', 'sublime', 'Arizona cannabis edibles brand.'),
  ('Ozone', 'ozone', 'Illinois cannabis flower brand.'),
  ('Revolution', 'revolution', 'Illinois cannabis flower brand.'),
  ('Legion of Bloom', 'legion-of-bloom', 'California cannabis vape & concentrate brand.')
on conflict (slug) do nothing;
