-- ════════════════════════════════════════════════════════════════════════════
-- 20260531000011_notifications
-- In-app notifications generated by order lifecycle events, delivered live via
-- Supabase Realtime. `device_tokens` stores FCM/APNs tokens for the native-push
-- last mile (see the send-push edge function).
-- ════════════════════════════════════════════════════════════════════════════
set search_path = public;

create table public.notifications (
  id          uuid primary key default extensions.gen_random_uuid(),
  user_id     uuid not null references public.profiles (id) on delete cascade,
  type        text not null default 'order_update',
  title       text not null,
  body        text,
  data        jsonb not null default '{}'::jsonb,
  read        boolean not null default false,
  created_at  timestamptz not null default now()
);

create index notifications_user_idx on public.notifications (user_id, created_at desc);
create index notifications_unread_idx on public.notifications (user_id) where not read;

alter table public.notifications enable row level security;

-- Recipients read / mark-read / delete their own. Rows are created only by the
-- SECURITY DEFINER trigger below (no client INSERT policy).
create policy notifications_select_self on public.notifications
  for select to authenticated using (user_id = auth.uid());
create policy notifications_update_self on public.notifications
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy notifications_delete_self on public.notifications
  for delete to authenticated using (user_id = auth.uid());

-- Live delivery.
alter publication supabase_realtime add table public.notifications;

-- ─── device_tokens (native push bridge) ─────────────────────────────────────
create table public.device_tokens (
  id         uuid primary key default extensions.gen_random_uuid(),
  user_id    uuid not null references public.profiles (id) on delete cascade,
  token      text not null,
  platform   text not null default 'unknown',
  created_at timestamptz not null default now(),
  constraint device_tokens_token_key unique (token)
);

create index device_tokens_user_idx on public.device_tokens (user_id);

alter table public.device_tokens enable row level security;

create policy device_tokens_select_self on public.device_tokens
  for select to authenticated using (user_id = auth.uid());
create policy device_tokens_insert_self on public.device_tokens
  for insert to authenticated with check (user_id = auth.uid());
create policy device_tokens_update_self on public.device_tokens
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy device_tokens_delete_self on public.device_tokens
  for delete to authenticated using (user_id = auth.uid());

-- ─── Order lifecycle → notifications ─────────────────────────────────────────
-- SECURITY DEFINER: the actor (dispensary owner advancing status, or buyer
-- placing an order) is not the notification recipient, so this must bypass the
-- recipient-scoped insert RLS.
create or replace function public.notify_order_event()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  shop_name text;
  owner uuid;
begin
  select name, owner_id into shop_name, owner
  from public.dispensaries where id = new.dispensary_id;

  if tg_op = 'INSERT' then
    -- Notify the dispensary owner of a new order.
    if owner is not null then
      insert into public.notifications (user_id, type, title, body, data)
      values (owner, 'order_new', 'New order received',
              'You have a new ' || new.order_type || ' order.',
              jsonb_build_object('order_id', new.id, 'status', new.status));
    end if;
    return new;
  end if;

  -- UPDATE: only on a real status change, notify the buyer.
  if new.status is distinct from old.status then
    insert into public.notifications (user_id, type, title, body, data)
    values (
      new.user_id, 'order_update',
      case new.status
        when 'confirmed' then 'Order confirmed'
        when 'ready' then 'Order ready'
        when 'completed' then 'Order completed'
        when 'cancelled' then 'Order cancelled'
        else 'Order updated'
      end,
      case new.status
        when 'confirmed' then 'Your order at ' || coalesce(shop_name, 'the dispensary') || ' was confirmed.'
        when 'ready' then 'Your order is ready for ' || new.order_type || '.'
        when 'completed' then 'Your order is complete. Enjoy!'
        when 'cancelled' then 'Your order was cancelled.'
        else 'Your order status changed to ' || new.status || '.'
      end,
      jsonb_build_object('order_id', new.id, 'status', new.status)
    );
  end if;
  return new;
end;
$$;

create trigger orders_notify_new
  after insert on public.orders
  for each row execute function public.notify_order_event();

create trigger orders_notify_status
  after update of status on public.orders
  for each row execute function public.notify_order_event();
